const clans = {
  brenni: 'Brenni',
  brenniDescription: `Characters from the <b>Brenni Clan</b> ride the line between civil society and the dark underworld of Justitian, and give an inroad for Players and their groups into the murky criminal networks of the city. They have some talent as healers, but their real value comes from their other skills, whether it’s their social maneuverability or their aptitude for creating deadly poisons. <b>While in Justitian, Brenni can apply their Allies Background to any of the city’s criminal elements - Carrion Birds, Cartel, or anyone else staying under the Judges’ radar.</b>`
}

const ranks = {
  'brenni-aide': 'Aide',
  'brenni-aideDescription': `They scurry about between the legs of the more experienced members of their Clan, rushing to and fro to bring reagents, herbs, chemicals, or medical supplies to their betters. They are apprenticed to a higher ranking Brenni, and they’d better learn quickly in order to make themselves useful.<br/><br/><b>PREREQUISITE:</b> -<br/><b>RESULT:</b> -<br/><b>EQUIPMENT:</b> Small notebook which is to be filled with recipes and notes from their mentor; Basic healing herbs for practice (+1D to INT+Medicine, single use).`,

  'brenni-guru': 'Guru',
  'brenni-guruDescription': `While they are yet to master the art of healing, still unable to mix together herbs and concoctions to create the miracle cures of the Alchemists, they have been able to extensively study and practise the crafts of physiotherapy, acupuncture, and more. Extensive knowledge of human anatomy allows them to fix a patient's inflamed tendons, relieve them from a lumbago, or increase their general mobility. Gurus provide first aid, give medical or nutritional advice, and release organic tissue from pain and stress.<br/><br/><b>PREREQUISITE:</b> INT+Medicine 6, INT+Science 5, INS+Perception 6<br/><b>RESULT:</b> Once a Guru begins making their first forays into the underground, they gain +1 Network related to Justitian’s underworld.<br/><b>EQUIPMENT:</b> Texts detailing the pressure points, energy paths, and chakras of the human body, giving them +1D to CHA+Expression or INT+Medicine when using those facts to heal a patient.`,

  'brenni-brewer': 'Brewer',
  'brenni-brewerDescription': `The Brewers of Brennen are some of the best in their field, and their spirits are famed among the people of the Protectorate. They have been able to land a job at a distillery or brewery in Justitian, and quickly find the Judges and other members of high society amongst their clientele. The Anabaptists, on the other hand, don’t yet know if they should consider the Brewers of Brennen as rivals or drinking buddies. Whatever the case, as a Brewer the Brenni can acquire some of the rarest spices to upgrade his brandies and liqueurs with goods normally unavailable on the civic markets; a special permit allows him to import uncertified stimulants from places like Liqua and out of the Jehammedan Quarter.<br/><br/><b>PREREQUISITE:</b> INT+Science 7, CHA+Arts 6, CHA+Conduct 5<br/><b>RESULT:</b> His newfound influence catapults him into Uptown and grants citizenship: he gains +1 Network point related to Justitian’s upper class.<br/><b>EQUIPMENT:</b> Citizenship papers; A bottle of the alcohol produced by his workplace.`,

  'brenni-toxician': 'Toxician',
  'brenni-toxicianDescription': `Once a Brenni continues on his journey into the shadows of the Clan, his work moves from the open street into the hidden back rooms and underground laboratories, where he hones his craft in creating ever more lethal concoctions and poisons for his more sinister clients. Toxicians require a spotless network of suppliers, often using Brewers as frontmen to gain access to chemical substances otherwise unavailable to them. Additionally, their expanded network allows them to import potent toxins via Justitian’s many black markets and have these caches stashed in secret locations across the city. A secret tattoo, featuring a serpent encircling the moon, identifies Toxicians to one another.<br/><br/><b>PREREQUISITE:</b> INT+Science 8, BOD+Toughness 6, PSY+Cunning 7<br/><b>RESULT:</b> -<br/><b>EQUIPMENT:</b> Keys to workshops and stores throughout Justitian; High quality herbs and chemicals (+1D to INT+Science when creating toxins).`,

  'brenni-apothecary': 'Apothecary',
  'brenni-apothecaryDescription': `The Apothecary sets himself apart from the crowd, developing his healing skills further and applying his arcane and mystical knowledge to create herbal remedies and cures that can drag heavily injured patients back from the brink of death. The Brenni is now the go-to doctor for the downtrodden and the criminals of Justitian, and he’s paid well in return - both for his services, and for his discretion.<br/><br/><b>PREREQUISITE:</b> INT+Medicine 8, INT+Legends 6<br/><b>RESULT:</b> Using their laboratories, Apothecaries gain the ability to produce a wide variety of substances with equally diverse effects. With a roll of INT+Medicine (5) they can create one dose of any standard pharmaceutical agent - stimulants, narcotics, antibiotics, and more - and for every (2) Triggers the drug’s level rises by 1.<br/><b>EQUIPMENT:</b> Extensive scriptures passed down from their ancestors on curative agents and herbal mixtures, giving them +2D to INT+Medicine; A laboratory in Brennen where they can conduct their experiments uninterrupted.`,

  'brenni-alchemist': 'Alchemist',
  'brenni-alchemistDescription': `The Brenni has been practising and studying his chosen discipline for a lifetime, and there are only a few areas that he hasn’t touched. Whether he turns his hand towards miracle cures or fatal poisons, whatever he produces is intensely effective or potentially deadly. Now he has access to the full resources of his Clan, along with the respect amongst the underground drug lords of the Cartel and the Carrion Birds. Furthermore he acts as the relay for commands issued by the secretive Meisters, calling meetings in underground halls and supposedly deserted chambers to inform the other Brenni of the contents of the messages he has received.<br/><br/><b>PREREQUISITE:</b> INT+Medicine or INT+Science 9, INT+Legends 6<br/><b>RESULT:</b> -<br/><b>EQUIPMENT:</b> Only the Alchemists have access to the reagents and knowledge required to perform the Red Purge, an ancient technique to expunge all toxins and poisons from a body. However, it is taboo for them to accept payment in coin, only a suitable favor is permitted.`,

  'brenni-meister': 'Meister',
  'brenni-meisterDescription': `It is said they can turn lead into gold, that they were fed by their mothers with blood instead of milk, and that they can perceive the lifeline of a human being by touch alone. The Meisters work in total obscurity, blending in with the common members of the Clan in their daily lives, distributing their orders to their brethren through coded messages and dead drops. What’s known: there are seven of them at a time, with each new member chosen by the other six only if one of them steps down or passes away. They direct the Brenni in their movements, and are more essential than ever now as they struggle to maintain their identity under the heel of the Spitalians and Judges. Each Meister is an unparalleled practitioner of their hermetic lore, and whenever they command an action it is backed with ancestral power.<br/><br/><b>PREREQUISITE:</b> Secrets 5, INT+Legends 10, PSY+Cunning 10<br/><b>RESULT:</b> -<br/><b>EQUIPMENT:</b> Keys to access the deserted dungeons of Brennen, where Brennus once performed his miracles. Now, they are used for the meetings of the Meisters.`,

  'brenni-inheritor': 'Inheritor',
  'brenni-inheritorDescription': `There can only ever be a single Inheritor. In times of great need, when the Brenni are on the brink of ruin, the Meisters gather to choose a suitable vessel for the spirit of their great ancestor, Brennus. The Inheritor imbibes an ancient mixture of potent chemicals and herbs which has been passed down through the Clan for generations, allowing him to contact and communicate with the original Founder of the Clan, receiving his instructions on the correct path through an emergency. Only three Inheritors have been chosen throughout the history of the Brenni, and each time they emerged from their spiritual journey with unearthly knowledge, cunningly navigating any obstacles in their path.<br/><br/><b>PREREQUISITE:</b> Chosen by the Meisters; Survived at least one Red Purge<br/><b>RESULT:</b> The Inheritor’s Authority, Allies, and Secrets scores can never be less than 6.<br/><b>EQUIPMENT:</b> A single vial of the ancient mixture, which wracks their body as it expands their mind, causing them to take (2) Trauma Damage; The robes of Brennus (+4D to interactions with Brenni).`
}

const potentials = {
  esotericCure: 'Esoteric Cure',
  esotericCureDescription: `The Brenni are masters of all kinds of esoteric and mystical remedies, some of which are nothing but placebos - not that the patients eagerly reaching for their wallets know that.<br/><br/><b>RESULT:</b> A roll on <b>CHA+Expression</b>, with <b>+1D per Potential Level</b>, against a target’s Mental Defense allows the Brenni to convince them of their “cure” enough to regain a single Ego Point or Flesh Wound. However, this can only be done once per day, and if a patient ever succeeds in their Mental Defense they can no longer be affected by the cure.`
}

const englishFallback = { clans, ranks, potentials }

export const brenniMessages = {
  de: englishFallback,
  en: englishFallback,
  fr: englishFallback
}
