const clans = {
  britoni: 'Britoni',
  britoniDescription: `The Britoni are the mirror of their land, and are inextricably interwoven into the fabric of the existing society. They follow their own path, refusing to be beholden to any Cult. Characters belonging to this Clan will find themselves part of a rugged, survivalist culture that spans the entire region, and will find kinsmen in every corner - but not all of them are as friendly and unified as they once were. <b>Britoni add +1 to their Allies Background when they are in their Clan’s territory.</b>`
}

const ranks = {
  'britoni-kelp': 'Kelp',
  'britoni-kelpDescription': `Just as seaweed can take root in every nook and cranny of shoreline nurtured by sea water, so too does the Kelp find their way into every aspect of Britoni society. They can be found all throughout the Northwest, sticking to the beaches and rustling beneath the footsteps of their more esteemed relatives. Eventually, they’ll grow up, leave their roots behind, and set out for something else.<br/><br/><b>PREREQUISITE:</b> -<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Small ivory token of Britoni heritage`,

  'britoni-waverider': 'Waverider',
  'britoni-waveriderDescription': `Land isn’t enough for him. Too stable, too safe, too barren. Out on the open waters of the Atlantic, clinging to a hunting boat as it rocks past the waves, harpoon raised and ready, that’s where a Waverider belongs. Alone against the might of the unforgiving sea he’d be swept away by the next gust, but in a hunting pack with a dozen other Britoni he pushes back against the tide.<br/><br/>Every week he sets out from his home port, going after seals, fish, and occasionally small whales. He is the provider for an entire family back home, taking everything he needs to feed his tribe. Even as he curses the rolling waves and bemoans the salt spray stinging his eyes, he nourishes thanks to the great life-giver of the Britoni – anyone who fails to respect the Grey Mother is destined to find themselves crushed between her merciless thighs.<br/><br/><b>PREREQUISITE:</b> INS+Survival 5, BOD+Melee 6<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Harpoon; Whalebone whistle to signal to his hunting pack`,

  'britoni-anchor': 'Anchor',
  'britoni-anchorDescription': `The sea molds the Britoni and cares for them, but not everyone can easily sprout flippers and rush out onto the waters. Instead, the Anchors have their own crucial role in the Clan. They rest ashore, arming the villages while Waveriders and Bullkillers are gone for the hunt. Anchors process the catch hauled back by their brethren; they carve up seals, strain out blubber, skin valuable pelts from sea lions, and strain oil from whale carcasses. In the evenings, they light the street lanterns or man the lighthouses to guide the hunters back to safety.<br/><br/>The Anchors are also responsible for handling trade between the many towns and settlements of the Britoni, ensuring that those located inland are kept supplied with food from the ports, and that other resources are correctly passed from village to village to ensure the entire region remains active.<br/><br/><b>PREREQUISITE:</b> INT+Science 4, AGI+Crafting 6, Network 2<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Workshop in their home town where they can process the catch of the day; Tools required for their work (Toolkit, Lvl 1)`,

  'britoni-bullkiller': 'Bullkiller',
  'britoni-bullkillerDescription': `Anyone can become a Waverider if they’ve got the guts to step away from the safety of land and take on responsibility, but that’s nothing but a drop in the bucket. The Bullkiller has stared a walrus down as part of the annual hunt and killed it in a fight, man against beast. He came away from the encounter battered and bruised, but victorious, claiming an ivory tusk which he will carve and engrave with his own personal epic.<br/><br/>Each Bullkiller is the focal point of an entire community, and represents the pinnacle of the lives of most Britoni. He is a symbol of masculinity, and an emblem of the Clan’s pride – one man defies the ocean, just as the Britoni defy the world. Now he leads a pack of Waveriders out on each foray, always looking for prey worthy of his skill: walrus bulls, sharks, and sea lions.<br/><br/><b>PREREQUISITE:</b> AGI+Navigation 6, CHA+Leadership 8, Renown 3, Killed a walrus during the annual hunt with their bare hands<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Jet-ski with mounted harpoon launcher; Carved ivory tusk bearing his legacy (Talisman, +1D)`,

  'britoni-balmer': 'Balmer',
  'britoni-balmerDescription': `While the Britoni thrive on the gifts the stormy Atlantic provides them, their lives are far from harmonious. Shipwrecks, feisty prey, hunts gone wrong, even just brawls in taprooms all give the hunters more than their fair share of injuries, and it’s the Balmer’s task to patch them back up. She works in Balsam Houses and healing shacks throughout Briton, relying on the old, tried and true ways of medicine to set her brethren back on their feet and send them on their way.<br/><br/>The Balmer does more than just heal the body, she also soothes the soul. She provides spiritual guidance for the members of her Clan, reads the guts of seals to predict future snowfalls, and performs rituals over those suffering from a vast array of ailments. The Anabaptists are unhappy with this remnant of the old traditionalist practices of the Britoni, but they lack the influence to purge it entirely.<br/><br/><b>PREREQUISITE:</b> INT+Medicine 8, INS+Empathy 6, Allies 3<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> She takes no payment for her services, but the gratitude received from her people leaves her wanting for nothing; A workshop where she can care for patients (+2D for INT+Medicine)`,

  'britoni-prow': 'Prow',
  'britoni-prowDescription': `The Prow cuts through the spray, resolute and implacable. He has proven himself to be exceptional in his own right, whether out on the waters leading a band of Bullkillers to bring down legendary prey, or on land forging communities and managing hundreds of his kinsmen. The Prow leads, and others follow. In times past he would act as the King’s personal advisor, counted among the closest members of Oppolus’ royal hunting party, but things have changed.<br/><br/>Now, the Prow must take on a more diplomatic role as the Oppolids attempt to divide the Clan amongst themselves. He acts as an advisor and mediator, using his weathered calm and steady nerves to resolve disputes between chieftains in a wide range of different harbors, representing the will of the Oppolid he’s sworn fealty to.<br/><br/><b>PREREQUISITE:</b> AGI+Projectiles 9 or BOD+Melee 9, INS+Survival 7, Renown 4, Authority 3<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Speedboat with pintle mounted cannon; Personalized insignia to paint on his shield or cloak; Symbol of his Oppolid`,

  'britoni-oppolid': 'Oppolid',
  'britoni-oppolidDescription': `Oppolus is – was – recognized by the Britoni as the greatest, wisest, and most decorated King of all. However, despite his long list of achievements and accomplishments, not everyone was as appeased by his rule. The Oppolids, his twelve natural born sons and daughters, looked on his blatant favoritism of his two Anabaptist brats with disdain and disgust; they all knew they were just as capable, they knew that they would be able to steer Briton on their own. Their moment has come.<br/><br/>The Oppolids have stepped up and taken charge in the aftermath of their father’s downfall, each carving out a small piece of the formerly united realm as their own. Each must choose his or her own method to rule. Does he crack down on his people with an iron fist, only to be rebuked by the rugged survivalist nature of the Britoni? Does she soothe worries and calm tempers with words of advice, only to find her people growing complacent in the face of the dangers arrayed against them? The Oppolids have a lot to live up to – only time will tell if they can handle the responsibility.<br/><br/><b>PREREQUISITE:</b> Directly descended from Oppolus or married to one of his children, CHA+Leadership 10, Renown 5<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Personal signet ring; Hunting horn with their symbol; Castle or stronghold from which they rule their domain`,

  'britoni-whaler': 'Whaler',
  'britoni-whalerDescription': `All of Briton knows the Whaler for his skill. If he wanted to be King he could snap his fingers and make it so, and the Oppolids wouldn’t dare stand in his way. However, he has far more important things to take care of.<br/><br/>The Whaler has more experience than anyone who ever traversed the Atlantic, and has ventured farther than any other competitor. He leads a team of handpicked Prows and Bullkillers out on his expeditions, and when the annual hunt during the Day of Ganaress rolls around, it’s his ship that draws the most attention and speculation – what mighty beast will the Whaler bring home today? He is always sought after by Neolibyans and Leopards, along with the best Scrappers of Saint Brieuc, to give advice on sailing paths or dead-zones in the current where floating debris might sink to the bottom. His great exploits, bringing down sperm whales and orcas, are part of what make him special, but not the only thing. His knowledge of foreign shores is worth the weight of a captured whale in gold.<br/><br/>Whenever he regales a crowd with tales of Gaelik, Iceland, or the foreign Azores, everyone is stunned into silence by these exploits they’ll never personally lay eyes on. As the Black Water slithers ashore, more and more eyes turn his way, especially as stories of great leviathans and hulking monsters rising from the waters filter out into the Clan. Maybe the Whaler will meet his match out in the Atlantic, facing down hell itself.<br/><br/><b>PREREQUISITE:</b> INS+Survival 10, AGI+Navigation 10, INS+Orienteering 10, Renown 5<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> His legendary stories and tales will have anyone falling head-over-heels to supply him with whatever he needs: the Whaler has Resources (6), and will never find himself lacking for equipment`
}

const potentials = {
  riptide: 'Riptide',
  riptideDescription: `The ocean buckles, towers above with fury, and crashes down, but the Britoni doesn’t give an inch. Whenever he gets hit, he weathers the blow and fights back harder, funneling the pain into boundless rage. He turns his anger toward his enemies and cuts them apart.<br/><br/><b>EFFECT:</b> When a Britoni attacks any opponent who has previously dealt Damage to him, he adds +1D per Potential Level to his Attack roll.`
}

const englishFallback = { clans, ranks, potentials }

export const britoniMessages = {
  de: englishFallback,
  en: englishFallback,
  fr: englishFallback
}
