const clans = {
  ganarids: 'Ganarids',
  ganaridsDescription: `The hive has been scattered and left as thousands of dispersed particles, each of them slowly finding their own path to safety and security. Ganarid characters are entirely unique, straddling two hierarchies as they hide within a greater Cult or Clan, masquerading as a regular member while still cognizant of their true nature - the inheritors of Ganaress’ kingdom, waiting for his return. They play a dangerous game, though: if their identity as insidious agents is discovered, they'll be executed with no remorse. Ganarids have an alternate character creation process, detailed in their rank hierarchy.`
}

const ranks = {
  'ganarids-grub': 'Grub',
  'ganarids-grubDescription': `He hasn’t yet found his purpose, or is still trying to piece together his individuality from the convoluted mass of the Ganarid collective. He quietly drifts through the hinterlands of Briton, or slips through the cracks of society as a faceless, nameless citizen of any number of villages and cities throughout Franka. People see him for what he is; a loner, a stranger, someone without his friends or partners. Any relationships he does strike up with the other dregs of civilization are trivial at best, and built on shaky foundations.<br/><br/>With Franka in turmoil due to a cascade of recent events, he’s in a dangerous position – humans resort to violence when frightened, and they inevitably direct their suspicion and retribution against outsiders, and unknowns. He must find himself a new identity, and do so quick.<br/><br/><b>PREREQUISITE:</b> Former member of Ganaress’ hive<br/><b>RESULT:</b> -<br/><b>EQUIPMENT:</b> Nothing but what he can scrounge up, cast aside by human society`,

  'ganarids-larva': 'Larva',
  'ganarids-larvaDescription': `Stage one of his development. The Larva has found a Cult or Clan which seems receptive to his infiltration. He gets entangled with its members, begins to ask the right questions, and eventually takes the plunge of joining them as an initiate. A tattoo to the brow and a nose ring through the septum turn him into a Touched one, while volunteering to defend Franka in the name of the ancient nation puts him into the uniform of the Resistance – he grits his teeth and soldiers on.<br/><br/>The Larva applies himself completely to the disguise, and sheds his identity as a Ganarid, at least on the outside. At night, in the dorms of the church or in the packed sleeping room of a Britoni inn, he still hears the whispers of the collective, of his people. They’ll keep him company.<br/><br/><b>PREREQUISITE:</b> INS+Empathy 5, PSY+Deception 4<br/><b>RESULT:</b> -<br/><b>EQUIPMENT:</b> A small, hand carved idol of Ganaress he keeps stashed away, hidden from anyone. It’s his only reminder of the past`,

  'ganarids-pupa': 'Pupa',
  'ganarids-pupaDescription': `Digging deeper, sinking further. The Pupa has risen beyond the lowest ranks of his chosen target’s hierarchy, and has begun to take on tasks for his superiors. He pretends to be nothing more than a driven, eager-to-please Agent rushing to-and-fro for a Mediator, or an industrious Badger jostling for position amidst the Mud Crabs on Briton’s many beaches. To his growing network of friends, contacts, and suppliers, that’s all he is, no reason for any additional suspicion. The Pupa has managed to secure a solid shell around himself, and has found some measure of safety in his current situation – but it’s not enough, not yet. He can still go higher, take on more responsibilities and make more connections, find a secure haven to wait out the months or years until the return of his King.<br/><br/><b>PREREQUISITE:</b> CHA+Conduct 7, PSY+Cunning 6<br/><b>RESULT:</b> -<br/><b>EQUIPMENT:</b> In a disused part of his barracks, or a ruined shack close to his church, he has created a tiny shrine to his King where he can reflect on everything that was taken from him`,

  'ganarids-imago': 'Imago',
  'ganarids-imagoDescription': `The Imago is so deeply entrenched in his new role that his superiors have even begun giving him responsibility over others. Now, along with his tightly knit and expansive web of contacts all linked back to his false identity, he has acquired a group of subordinates and allies he can call upon in times of stress. No outsider would dare question his origins or background now, and he’s built up enough goodwill that any challenger from the inside will be subtly pushed into silence. He leads hunts out onto the waters as a Britoni Bullkiller, recalls the great human history of Franka as a Savant of the Resistance, and preaches the word of the Neognosis as an Elysian. The Ganarid can relax, his masquerade complete.<br/><br/>Except, the murmur of the collective keeps growing stronger, the memories of his kin mixing into his dreams, a call growing louder and louder with each passing day. He’s not finished yet. One last step.<br/><br/><b>PREREQUISITE:</b> CHA+Leadership 6, CHA+Expression 8, INS+Empathy 8<br/><b>RESULT:</b> -<br/><b>EQUIPMENT:</b> He can’t be overt about his worship, but he does as much as he can to stave off the voices in his head. He finds opportunities to slip away to a large shrine, far out of sight, where he connects with his detached brethren. Soon, the time will come when they can truly reunite.`,

  'ganarids-moth': 'Moth',
  'ganarids-mothDescription': `Ascendent. The Moth sheds the trappings of his infiltrated target, emerging from the cocoon of disguise to take on a blazing new form. His stigma has reawakened, whether due to an imperfect removal or a heavy dose of new Sepsis infestation, and the ether has chosen him to be a new Idol bearer – even if he represents a King which no longer exists, and is yet to be reborn. He is a leader to the other Ganarids, infecting them with his vision and determination, guiding them towards the light.<br/><br/>He directs the Ganarids throughout Briton and beyond, subtly influencing them with instructions broadcast through their collective unconscious. His mind is strong, and his voice firm as the members of his hive find themselves dancing to the tune of their superior. When the time comes, he will take his rightful place at Ganaress’ side, heft the banner of the true King, and stand at the crest of an army which will sweep across the land. The mistakes of the past will not be repeated this time.<br/><br/><b>PREREQUISITE:</b> PSY+Faith/Willpower 11, PSY+Domination 9, CHA+Leadership 10<br/><b>RESULT:</b> -<br/><b>EQUIPMENT:</b> His hands worked on autopilot, carving out the shapes using the skills and knowledge of his kin. Now, the Idol mask rests on his face, and commands all other Ganarids to answer (Talisman, +3D)`
}

const potentials = {
  harmonious: 'Harmonious',
  harmoniousDescription: `<b>PREREQUISITE:</b> Spore Infestation (5)<br/><br/>Unconsciously, the Ganarids have been sharing their collective identity ever since they were inducted into Ganaress’ hive. Despite the loss of their King, the connection to the rest of the hive remains, however tenuous, and in times of need the Ganarid can access the skills of his brethren. In a stressful situation, the Ganarid can spend up to the Potential level in Ego Points to raise the value of a single Skill of his choice by the same amount for the duration of a scene, once per day.`
}

const englishFallback = { clans, ranks, potentials }

export const ganaridsMessages = {
  de: englishFallback,
  en: englishFallback,
  fr: englishFallback
}
