const clans = {
  pictons: 'Pictons',
  pictonsDescription: `Two hundred years ago, the Pictons were introduced to their God, Argyre. He made them grasp their true purpose, and turned them into attack dogs hunting down his enemies and delivering his revenge. To fulfil their destiny they were bestowed with bleeding edge technology, while their bodies were warped to operate far beyond normal human capacity. Yet the Pictons are also intensely superstitious, fearing the ire of their Carrion Lord more than any mortal opponent, and savage. Their worship and deeply implanted memetic subroutines make them obedient and zealous, while also shielding them from mental strain - <b>Picton characters add +1S to all Mental Defense rolls.</b>`
}

const ranks = {
  'pictons-orbiter': 'Orbiter',
  'pictons-orbiterDescription': `Like scattered debris they drift through Argyre’s territory, unfocused and with unfinished conditioning. They paint themselves in the Vulture’s symbols, gaze up in awe at the stars, but they don’t understand – not yet. By day they return to the subterranean world of their Clan, where the Meme Chambers and video screens show them glimpses of the wonders that once were. If they’re lucky, they’ll even see a flash of their God, his scarred and twisted visage giving them a glance, nothing more.<br/><br/><b>CONDITION:</b> -<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> A can of glowing paint and a few scraps of food. It’s all they deserve for now`,

  'pictons-trajector': 'Trajector',
  'pictons-trajectorDescription': `The Trajector no longer orbits aimlessly. Now he hunts. His indoctrination has proceeded far enough that he is permitted to venture out to keep the Rotten God’s domain secure. He isn’t yet allowed to go after the world killers, so instead he patrols the borders of Britain, tearing apart those reckless or foolish enough to cross into Argyre’s kingdom. Anything he kills he brings back to the warrens beneath London, where it can be reused or eaten.<br/><br/>In the dark, bright symbols flash before his mind’s eye. The memetics are setting in, taking control, and his fear of the Vulture has grown into zealous obedience – if only to guarantee survival. One of his broodmates, the least productive, was chosen for a demonstration of Argyre’s power, and he still sees the horrifying sight whenever he blinks. He will not fail.<br/><br/><b>CONDITION:</b> BOD+Toughness 6, INS+Survival 5<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Automatic pistol; Serrated knife (Modified knife with Gruesome (2))`,

  'pictons-booster': 'Booter',
  'pictons-boosterDescription': `Just as a satellite needs a rocket to propel it into orbit, the Pictons roaming across Britain need the Boosters to push them to new heights. They toil away in the deep chambers of Argyre’s demesne, watching over the cultivation vats and hormone farms which are used to create the star food, the Vulture’s gift to his hellhounds. It fuels the body, ensures the mind is ready for conditioning, and allows anyone to operate at a level close to the Ambrosia induced world killers.<br/><br/>Chemicals can be harvested using their God’s technology, but the meat to feed the Pictons must be sourced from elsewhere, either from corpses dragged in by the Trajectors or sliced from the bodies of those who failed the Rotten God. Palers are a snack. Scrappers a full meal. Everything is taken and reused.<br/><br/><b>CONDITION:</b> AGI+Dexterity 5, INT+Science 6, Secrets 2<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Access to Argyre’s outlying laboratories, giving +2D on any INT+Science rolls to create drugs or chemical substances`,

  'pictons-stareater': 'Star Eater',
  'pictons-stareaterDescription': `The Star Eater has ascended beyond the limits of the puny scavengers scrabbling around the edges of the Rotten God’s realm. The star food has made him strong, made him fast, made him resilient. He can shrug off injuries that would have killed his former self and push his body to the absolute maximum. His conditioning is pristine, every thought tinted with fearful reverence and every impulse done in accordance with glowing symbols blazing in his mind. He doesn’t understand them, but he still recognizes and follows their instructions.<br/><br/>The Vulture has decided that the Star Eater is ready and able to begin hunting the world killers, and the memetics in his head have been tuned to inspire absolute and endless hatred for the Sleepers and their actions. The Star Eater uses the tools of the Rotten God to devastate his prey and drag them kicking and screaming back to Argyre’s labor camps. They killed the world, but he eats stars. He wins.<br/><br/><b>CONDITION:</b> BOD+Stamina 7, INT+Legends 6, PSY+Cunning 6, Secrets 2<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Star food; Submachine gun with any modifications he can strap or bolt on, up to 2 Slots`,

  'pictons-deathwalker': 'Death Walker',
  'pictons-deathwalkerDescription': `The other Pictons shrink back as he approaches, even though they know he’s needed. The warriors have returned with broken bodies, one of the females has had a difficult birth, an improperly stitched wound has torn open again. He bears a polished disc in his right hand, sharpened to the point it parts flesh like water, and in his left he holds a small kit filled with the pastes and extracts developed for this purpose in the Rotten God’s deepest chambers. The process will be painful, but the Death Walker will ensure their mortal frames work again – or he will see to it that their cadaver is put to better use. It’s all the same in the eyes of the Vulture.<br/><br/>The Death Walker has been inducted and trained in the art of repairing the shells of Argyre’s hellions, keeping them moving even past the point where a lesser creature would be limp and lifeless. He adorns his skin with bright markings triggering the memetic patterns of panic and fear in his subjects, and he hides his face with a horrifying mask – terror provides the adrenaline to fight on. This, of course, requires that the subject be restrained and operated on without painkillers, but this is irrelevant. They will be healed or they will be recycled.<br/><br/><b>CONDITION:</b> CHA+Expression 6, INT+Medicine 8, PSY+Domination 7, Secrets 3<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Death Walkers are bestowed with strange medicines and medical equipment created by Bygone machines in Argyre’s labs, but they were designed with function rather than comfort in mind. He adds +4S to all INT+Medicine rolls to patch up other Pictons, at the cost of inflicting (4) Ego Damage whenever he conducts an operation`,

  'pictons-nebula': 'Nebula',
  'pictons-nebulaDescription': `The Vulture has permitted him to access the deepest sections under London, the steaming maze filled with the stench of rotten flesh and decorated with the perfectly preserved corpses of the world killers. He has been shown the idyllic environments of the past in the holo-chambers, walked through the Vulture's hydroponic gardens, and been made to understand the necessary justice he is delivering to the Sleepers in the name of his God.<br/><br/>The Nebula has also been given a limited degree of access to the memetic programming swirling through the minds of the Pictons under his command, which he uses to his benefit out in the wastelands to embolden his Star Eaters while they hunt for signs of the Vulture’s sworn nemesis buried in the dust. He is well aware that the same commands and triggers exist in his head, but he gives it no further thought – the Rotten God is never to be questioned.<br/><br/><b>CONDITION:</b> BOD+Melee or AGI+Projectiles 8, CHA+Leadership 9, PSY+Domination 9, Secrets 4<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Anti-Sleeper artifacts from the vaults as needed for his missions (Deadbolt, Achilles, Deception Matrix); Void Grenades; Argyre’s yoke`,

  'pictons-gemini': 'Gemini',
  'pictons-geminiDescription': `Argyre is all-powerful, but not even he can monitor every corner of his realm at once, much less organize the hordes of Sleepers being worked to death in his labor camps. As such, he appoints a Gemini to oversee his kingdom while his attention is on more critical matters. The Gemini is given control over the yokes around the necks of the prisoners, allowing him to correctly motivate any rebellious or reluctant world killers with a burst of blinding pain.<br/><br/>Additionally, the Gemini is responsible for the mental programming of the lower ranking Pictons. He defines their memetic routines in the Meme Chambers, modulates the pitch and tone of the subliminals broadcast all throughout the warrens, and evaluates the overall progress of each clutch to ensure they are developing correctly. Only Argyre himself could override the Gemini’s influence.<br/><br/><b>CONDITION:</b> INT+Science 9, PSY+Cunning, Deception, or Domination 11, INS+Taming 8, Secrets 5, Chosen by Argyre<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Code plate which can be used to flash up symbols to control the Pictons with memetic imagery (+4S to CHA+Leadership against other Pictons); Master control circuit for Argyre’s yoke`,

  'pictons-pulsar': 'Pulsar',
  'pictons-pulsarDescription': `None shine brighter than the Pulsar. He has been chosen as Argyre’s herald to the wretches crawling around the corpse of Europe, given the most critical tasks which the Rotten God cannot accomplish due to his banishment by the Free Spirits. He has been equipped with arsenals that could topple entire Clans in the blink of an eye, and can command the full cooperation of any other Picton with but a simple order. Only one Pulsar is ever chosen, and each is fully aware that their service ends only with their death. That’s just fine, it’s what God wants. The last three perished venturing into Borca to confront the Sleeper Prophets of Exalt and disable their Corresponder. Time to try again.<br/><br/><b>CONDITION:</b> BOD+Toughness 10, BOD+Force 8, CHA+Leadership 9, Authority 5, Chosen by Argyre<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Starfield, allowing him to communicate with Argyre even in distant lands; Any offensive artifact from the Vulture’s vault, personally modified to be as lethal as possible`
}

const potentials = {
  implantedExpertise: 'Implanted Expertise',
  implantedExpertiseDescription: `The Picton has been implanted with an untapped reserve of training and knowledge, deep in the recesses of his subconscious mind. This expertise is inaccessible unless in conjunction to a situation related to his task, set by Argyre himself. A single Skill per Potential level, chosen by the Game Master, suddenly rises by a number of Points equal to the Picton’s rank value for a single scene, even beyond the normal limit of 6, but the benefits collapse soon thereafter. The Picton is unable to reconjure the information that has only been implanted, never truly experienced.`
}

const englishFallback = { clans, ranks, potentials }

export const pictonsMessages = {
  de: englishFallback,
  en: englishFallback,
  fr: englishFallback
}
