const clans = {
  providers: 'Providers',
  providersDescription: `Provider characters take their place in a tight-knit family group, toughened from the labor in the fields and able to weather any sort of abuse. As characters they bring the clout of their bloodline with them into every confrontation, along with the strength that comes from heaving around heavy farming tools all day, and a knowledge of the Rubble which can’t be matched. <b>They add +1 to their Allies Background while in and around Justitian.</b>`
}

const ranks = {
  'providers-runner': 'Runner',
  'providers-runnerDescription': `They know how to chop off a chicken’s head, milk the cow, and mill the grains. What they lack in strength, age, or responsibility, they make up for with simple tasks, such as handling communication between the different Provider communities, rushing back and forth as messengers for their elders. In this manner, they get to know all of their relatives in the different settlements across the Rubble, and similarly they all get to know the Runner. Eventually they’ll meet their teenage sweetheart on one of the open fields this way.<br/><br/><b>PREREQUISITE:</b> -<br/><b>EFFECT:</b> They add +1 to their Allies Background score.<br/><b>EQUIPMENT:</b> A good pair of boots; Messenger bag; Sketched out maps of the Rubble`,

  'providers-bruiser': 'Bruiser',
  'providers-bruiserDescription': `By now, news about the Cooperative has spread throughout Downtown. Standing up to the mighty Justitian, a group of farmers finally digging in their heels and refusing to give up another inch of the ground they fought so hard to cultivate. The organization is idolised by the Providers, even if many are still too scared of reprisal to join themselves.<br/><br/>Bruisers are the muscle of the Cooperative, showing face whenever there’s a Provider in trouble whether he’s part of their organization yet or not. A Hygienist inspecting a farm is confronted with a pair of beefy ranchers to remind him that he’s at their mercy out here. A Juryman browbeating a family into paying him a tithe is dragged into a barn and tossed out with a black eye. The Bruisers keep the parcels safe, if only as a deterrent against the abuse of power.<br/><br/><b>PREREQUISITE:</b> BOD+Melee 6 or BOD+Brawl 6, Allies 2<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Shortened farm tools (Practical enough for plausible deniability, but more effective as weapons)`,

  'providers-harvester': 'Harvester',
  'providers-harvesterDescription': `The Harvester knows his land better than any high-and-mighty doctor with a shaved head and neoprene suit ever will. He tastes the wind to predict the next dust storm rolling through, how to lay out his crops so the roots grow best, and he can tell when his donkey is about to fall ill and needs rest. He’s spent long, arduous years accumulating experience under his parents’ tutelage, and now he’s putting it to good use.<br/><br/>The bulk of the Provider population is made up of Harvesters, each of them working for their relatives throughout the seasons. Eventually, during one of the annual Harvest festivals, they and their sweetheart will finally tie the braided rope knot representing two bloodlines becoming one and enter into marriage. Now, it’s time to work on starting up a new family line.<br/><br/><b>PREREQUISITE:</b> BOD+Force 6D, BOD+Stamina 6D, INS+Survival 6D<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Donkey and cart inherited from their parents; Keys to access the communal Provider storehouses; Permission waivers to own property in the Rubble`,

  'providers-vandal': 'Vandal',
  'providers-vandalDescription': `Every movement needs its goons, but without direction the Bruisers would just aimlessly mill about without any strategy. Ardon himself can’t direct the thousands of members throughout the Rubble, and as such, a more local leadership cadre is needed. That’s where the Vandals come in.<br/><br/>They are the Cooperative’s enforcers, each tasked personally by Ardon with the goal of managing a sector of Provider territory. Within their assigned patch of land, they are the core of the group’s presence. They set targets for the Bruisers, cozy up with the local Brigadiers and Patriarchs, and get to know every Protector and Juryman assigned to the region - hunting for blackmail material. They are identified by a tattoo of the Cooperative’s crest on their forearm, a crossed cleaver and scythe.<br/><br/><b>PREREQUISITE:</b> PSY+Domination 8, CHA+Leadership 8, Authority 4<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Tattoo of the Cooperative (Talisman, +1D PSY+Faith/Willpower); Encryption key for passing messages to other Vandals`,

  'providers-supplier': 'Supplier',
  'providers-supplierDescription': `While some Providers handle the entire process of planting, harvesting, and selling their goods alone, the smart ones let the Suppliers do it. Way back in their family history, one of their ancestors was gifted to or chosen by one of the great Advocate families, or a similarly powerful group in Uptown. It was only a small interaction, but Providers take every opportunity they can get. Using their family connections they were able to sneak their way into Justitian and wrap their heads around its labyrinthine systems.<br/><br/>Now, the Suppliers use their knowledge and contacts to exploit Justitian as much as possible to make good profits for their fellow Providers, along with securing any of the resources their brethren require to keep their farms running. The other farmers simply look on in confusion and shrug - they don’t get it, but it makes them money, so who cares.<br/><br/><b>PREREQUISITE:</b> CHA+Negotiation 7D, PSY+Cunning 7D, Network 4<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> List of sellers and market stalls that are receptive to their goods; Notebook filled with notes on sales and profits`,

  'providers-brigadier': 'Brigadier',
  'providers-brigadierDescription': `While the years of turmoil following the Providers relocation into the Rubble left many of their cultural and religious frameworks battered and broken, it was the Brigadiers who were able to carry the Clan through the storm and emerge intact on the other side. They have started a family of their own, putting their offspring to work as Harvester, and using their newfound liberation from the backbreaking labor of the fields they turn their hand towards a different kind of cultivation.<br/><br/>The Brigadier has learned the basic building blocks of the Providers’ sacred rituals from his own parents as a Harvester, but only now does he fully immerse himself. He orchestrates the marriages of his children, organizes the preparations of the yearly Harvest festival, and leads the celebration of Providers who pass away. In good years the Brigadier is a symbol of prosperity, in bad years, he is the rock of wisdom.<br/><br/><b>PREREQUISITE:</b> Started a family, INS+Survival 8D, INT+Legends 6D<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Permission waivers to own property in the Neighborhood of the Providers`,

  'providers-juryman': 'Village Juryman',
  'providers-jurymanDescription': `A Provider who manages to distinguish himself from his peers in the eyes of a Judge will be elevated to the post of Village Juryman. He receives his very own insignia and the approval of the Judiciary to dish out justice. In the eyes of the law, he’s now the penultimate authority in the Rubble, second only to the Judges themselves.<br/><br/><b>PREREQUISITE:</b> Sponsored by an existing Judge, Basic understanding of the Codex, Ability to read and write, BOD+Melee 6D, PSY+Domination 6D<br/><b>EFFECT:</b> For some, this is the opportunity they’ve been waiting for. They use their newfound power to give back to their families, and add +1 to their Allies Backgrounds. Others, however, see this as a chance for personal gain beyond their wildest dreams. They instead add +3 to their Network Background with the Judges, but can no longer use their Resources with their own Clan.<br/><b>EQUIPMENT:</b> Juryman insignia, allowing them to pass judgement on minor crimes and carry weapons in Justitian; Citizenship papers`,

  'providers-patriarch': 'Patriarch',
  'providers-patriarchDescription': `The Patriarch reigns among the Providers, ruling over a host of families related by blood. He presides over his small kingdom from a home passed down from generation to generation, filled with iconography of the harvest gods and symbolism depicting the Providers and their heritage.<br/><br/>Patriarchs are also responsible for administering justice within the Clan. When a Harvester brings an accusation against another Provider for adultery, or a Supplier is caught skimming an unjust profit, they are brought before the Patriarchs of the bloodlines involved. The two elders will listen to the stories of each, pray for guidance, and deliver a verdict. In severe cases, the guilty party is exiled from the Clan completely, marked with an ancient symbol of a tree split down the middle to brand him as a pariah.<br/><br/><b>PREREQUISITE:</b> Several successful farms operated by their offspring, Authority 5, CHA+Leadership 10D<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Permission waivers to own property in Fielding; A cohort of farms and communities owned by their offspring who all call them their Patriarch`
}

const potentials = {
  earthbound: 'Earthbound',
  earthboundDescription: `No matter where they are, or how desolate the environment, the Providers will make it work. They have tremendous knowledge of herbalism and geology, and know exactly how to reap the best from the land.<br/><br/><b>EFFECT:</b> They add +1S per Potential Level to all <b>INS+Survival</b> rolls to forage for food or find supplies in the natural landscape around them.`
}

const englishFallback = { clans, ranks, potentials }

export const providersMessages = {
  de: englishFallback,
  en: englishFallback,
  fr: englishFallback
}
