const clans = {
  steelmasters: 'Steel Masters',
  steelmastersDescription: `Steel Master characters are uniquely positioned. No one else is granted so much by the Judges: protection, high quality equipment, and an impenetrable fortress for a home. At the same time, they are placed under strict limitations, and must receive permission from the Judges to move throughout the city. However, they are far from defenseless; a hammer that can bend steel can easily break bone. <b>Steel Master characters can apply their Allies and Resources Backgrounds to the Judges.</b>`
}

const ranks = {
  'steelmasters-fledgedling': 'Fledgling',
  'steelmasters-fledgedlingDescription': `The colossal forges of the Steel Masters are never empty, but the spirits abhor wastefulness. The task of the Fledglings in the workshop is to recover the slag from the top of the melted metal before it is cast, so it can be recycled and reused. A life of humility lies ahead of them, as they begin their training as craftsmen in line with the family’s traditions, shadowing a Shaper or Metallurgist while they work.<br/><br/><b>CONDITION:</b> -<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Skimming rod and bucket; Rudimentary safety gear (heavy gloves, leather apron)`,

  'steelmasters-shaper': 'Shaper',
  'steelmasters-shaperDescription': `The sound of their hammers rings out across the city as they shape and temper the steel into its final form. Shapers are the sum of the Clan’s workforce, toiling ceaselessly to craft the Judiciary’s war machine.<br/><br/>When not on shift in the Steel Monolith’s workshops, they retreat to the Ogota chambers where they spend their time studying the works of the Steel Masters of old, attempting to gain insight into their expertise at manipulating the elements that make up the world and soothing the spirits through meditation and prayer. They blend spirituality with forging techniques and turn worship into work.<br/><br/><b>CONDITION:</b> Ogota, AGI+Crafting 7, BOD+Force 6<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Smithing hammer; Blacksmithing gear; Steel Master Clan insignia`,

  'steelmasters-metallurgist': 'Metallurgist',
  'steelmasters-metallurgistDescription': `While the Steel Masters are kept well supplied by the Judges, the quality of their raw material leaves much to be desired. It is the responsibility of the Metallurgists to ensure that only the highest quality scrap is melted down for final use, and to control the additives in the steel to maintain its strength. They are permitted to access the lowest levels of the Steel Monolith, inspecting and rejecting anything they deem unsuitable.<br/><br/>While they still maintain the core tenets of the Steel Masters’ beliefs, Metallurgists are far more grounded than their Ogota brethren - they have to be, otherwise they’d never get along with the Ropers in the Powder Mill, or the Scrappers who haul in the piles of recovered metal from the Ironworks.<br/><br/><b>CONDITION:</b> Gotokai, INS+Perception 6, INT+Science 7<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Restricted Downtown pass; Logbook for materials`,

  'steelmasters-foreman': 'Foreman',
  'steelmasters-foremanDescription': `The Foreman is given the task of venturing out into Downtown to seek out the discarded detritus that will be used by the Steel Masters to create the useful tools the Judiciary needs. He cooperates with the Judges as he trawls through the scrapyards of Tech-Central, and is given permission to hire up to 10 Scavengers to haul material back to the Steel Monolith.<br/><br/>Downtown is an unfamiliar and strange place for the Foremen, and every one of them will react differently to the experience of mingling with the unwashed masses of Justitian. Some watch the passersby with mouths agape, baffled by the strange habits of these people. Others are disgusted by the lack of cleanliness and respect on display. Only one thing is universally recognized: things make much more sense in the Monolith.<br/><br/><b>CONDITION:</b> Ogota, CHA+Negotiation 6, Network 3<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Procurement Permit, giving the Foreman access to Downtown to make purchases for the Steel Masters`,

  'steelmasters-overseer': 'Overseer',
  'steelmasters-overseerDescription': `The Judges always need more firepower, and the flow of work orders is neverending. Despite that, they refuse to accept even the slightest lapse in quality, and as such the responsibility of the Overseers never ends. The Overseer supervises their brethren, performing final checks before they are sent out to the Judges. He has full authority over other Steel Masters on the workshop floor, and can reject any work that doesn’t meet his standards.<br/><br/>Lately, more and more parts have been discarded due to poor material quality. The Overseers have been scrambling to track down the cause for months, now, but their progress has been blocked. The Ogota Foremen refuse to speak to the Gotokai Overseers in everything but the most cursory fashion, and any attempt to seek out an explanation for the poor steel being sent to the Crown is met with a curt dismissal. As the schism deepens the division between the families, a solution seems impossible.<br/><br/><b>CONDITION:</b> Gotokai, CHA+Leadership 8, INS+Perception 8, Authority 3<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Overseer badge; Proofing tools (Measurement instruments, special symbol to be hammered into parts when complete and marked for approval)`,

  'steelmasters-artificer': 'Artificer',
  'steelmasters-artificerDescription': `He has been working for years, learning how to mold and lull the spirits to create the most effective and prized weapons in the Judicial arsenal. His work is so renowned and effective that he has been personally named by an Executioner or Arbiter to create a masterpiece of blacksmithing for their personal collection.<br/><br/>The Artificers blend the two families of the Steel Monolith, combining the expertise of both bloodlines in a single caste of expert craftsmen. Traditionally, they are supposed to abandon any of the prejudices of their background. In practice, though, the schism rippling through the Steel Masters has affected the Artificers just as much, and despite working to keep up appearances the cracks are beginning to show. How can they pretend to work together when not even their family leaders can see eye-to-eye?<br/><br/><b>CONDITION:</b> AGI+Crafting 8, CHA+Arts 7, Network 4<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> A personal workshop where they are given the best materials and equipment, along with a Judicial patron who sponsors their work`,

  'steelmasters-steelmasterogota': 'Steel Master: Ogota',
  'steelmasters-steelmasterogotaDescription': `It can’t go on like this. The Steel Masters are slowly withering away, and the reason couldn’t be more clear to the current Ogota Steel Master, Danislai. Distraction.<br/><br/>The Gotokai branch of the family have become obsessed with leaving the safety and sanctity of their home in the clouds, proclaiming their reasons to be “bringing new talent into the fold”, but that isn’t the real truth. They’ve grown too weak to handle the responsibility of their bloodline, the knowledge of their unique heritage which must not be sullied.<br/><br/>There can only be one solution; for the Steel Masters to survive the Gotokai must be made to understand that the Steel Monolith is where they belong. If only Heza saw it too. Until then, Danislai focuses on his own position as the unparalleled master craftsman of the Steel Masters, able to do on his own in a day what a team of Shapers would struggle to match in a week.<br/><br/><b>CONDITION:</b> Danislai Ogota choosing a suitable successor from his offspring, AGI+Crafting 11<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Key to the Judges’ arsenal; The Flag (passed down from his ancestors, regenerates 1D Ego every time he meditates over the symbol); Access to the crown of the Steel Monolith, the sacred grounds where only the leaders of each family may go`,

  'steelmasters-steelmastergotokai': 'Steel Master: Gotokai',
  'steelmasters-steelmastergotokaiDescription': `It can’t go on like this. The Steel Masters are slowly withering away, and the reason couldn’t be more clear to the current Gotokai Steel Master, Heza. Isolation.<br/><br/>The Clan has been trapped in the Steel Monolith for generations, prohibited from bringing in new blood, learning new techniques, or even indulging in any luxury. The Ogota say that this is for the best, that the ruffians in Downtown would ruin the purity of their line, but that isn’t the real truth. They’ve just grown too comfortable with captivity, like a bird too terrified to leave its cage even when the door is open.<br/><br/>There can only be one solution; for the Steel Masters to survive the Ogota must be made to understand that staying confined in this prison cell is an impossibility. If only Danislai saw it too. Until then, Heza does his best to maintain the standard of his Clan’s work as their most skilled inspector, capable of spotting at a glance defects the current crop of Overseers would need hours of measuring to detect.<br/><br/><b>CONDITION:</b> Heza Gotokai choosing a suitable successor from his offspring, AGI+Crafting 11<br/><b>EFFECT:</b> -<br/><b>EQUIPMENT:</b> Key to the Judges’ arsenal; Ancient nautical map of the route taken by the ancient barges (passed down from his ancestors); Access to the crown of the Steel Monolith, the sacred grounds where only the leaders of each family may go`
}

const potentials = {
  spiritshaper: 'Spiritshaper',
  spiritshaperDescription: `The Steel Master has gained an understanding of the spirits, able to work with diligence and patience to tame and influence them to achieve perfection.<br/><br/><b>EFFECT:</b> He gains +1S per Potential level to all <b>AGI+Crafting</b> rolls related to weapon smithing.`
}

const englishFallback = { clans, ranks, potentials }

export const steelMastersMessages = {
  de: englishFallback,
  en: englishFallback,
  fr: englishFallback
}
