const bordenoirRanks = {
  'bordenoir-mouton': 'Mouton',
  'bordenoir-moutonDescription': `<b>PREREQUISITE:</b> -<br/><b>RESULT:</b> The Bordenoir remember their history, a disparate, unfocused conglomerate of Clans compressed until the breaking point came. The union of the old, separated families and tribes was what gave them strength in the past, and it’s what gives them identity today. Anyone who is willing to contribute can become a member of the Bordenoir, no matter their origin or background. Frankans, Hybrispanians, Africans, it doesn’t matter. They are all marked with the insignia of the Bordenoir, a tattoo with ink made from black soot, placed on the back of the hand, allowing any member of the Clan to recognise his new brethren.<br/><br/>From there, the newly crowned Mouton gets to work in and around Perpignan. As fishermen, blacksmiths, bakers, butchers, farmers, and almost any other niche, the Mouton contributes to his new Clan, and proves his worth.<br/><b>EQUIPMENT:</b> Excellent maps of the Pyrenees and the southern coast of Franka`,

  'bordenoir-capricorne': 'Capricorne',
  'bordenoir-capricorneDescription': `<b>PREREQUISITE:</b> BOD+Athletics 6, AGI+Crafting 6, Allies 1<br/><b>RESULT:</b> There are two distinct disciplines breaking away from the traditional path of the Bordenoir, and the Capricorne has chosen to follow one. The monotony of toiling away in a shop or farm doesn’t appeal to him, and he doesn’t have the sea legs to spend all day every day out on a boat catching fish. Instead, he turns his eyes to the Pyrenees, buying or renting some excavation gear and joining up with a team heading along the old mountain paths. Up there he and his fellow Clanners get to work digging into the guts of the earth, chiseling chunks of ore from the walls of the ancient tunnels or creating new branches to the mines. When his team hauls the score back to Perpignan or to the camps of the Jehammedans living nearby, he gets a share of the profit for his effort.<br/><br/>While up in the mountains, he makes contact with the Jehammedans and becomes good friends with the Abrami and Ismaeli of the tribes. They’ll let him pass along the safer paths without paying a toll, and give him some advice on how to handle these areas: the Capricorne adds <b>+2D to INS+Survival and BOD+Athletics</b> in mountainous terrain.<br/><b>EQUIPMENT:</b> Climbing gear; Pickaxe`,

  'bordenoir-faucon': 'Faucon',
  'bordenoir-fauconDescription': `<b>PREREQUISITE:</b> BOD+Toughness 4, AGI+Projectiles 6, AGI+Navigation 6<br/><b>RESULT:</b> The rushing wind whips through his hair, the spray from the waters below makes the air taste of salt, the sway of his ship forces him to adjust his balance. It all feels right. The crack of a cannon breaks the moment as the Faucon gets to work, defending his people and home.<br/><br/>Out on the Mediterranean is where the Faucon knows he belongs, and his task is essential. Franka is a dangerous place, with strange beasts prowling inland and vicious pirates circling offshore. The massed ranks of the Bordenoir need defending from these threats, and the Faucon provides. He takes up the sword and harpoon, patrolling the waters and land around Perpignan, keeping the Moutons safe—to them, he’s a hero. The Faucon gains <b>Allies (+1)</b>.<br/><b>EQUIPMENT:</b> Pneumatic harpoon (harpoon crossbow); Dhow; Binoculars; Flare gun`,

  'bordenoir-mineur': 'Mineur',
  'bordenoir-mineurDescription': `<b>PREREQUISITE:</b> AGI+Crafting 8, INT+Legends 6, INS+Orienteering 6, Network 2, Resources 2<br/><b>RESULT:</b> Anyone with a modicum of common sense and a bit of brawn can grab a pickaxe and start digging. Good enough to scrape by, picking up a few chunks of iron or silver here and there, but that’s not where the real money lies. The Mineur has shown the spark of ingenuity needed to track down the worthwhile spots, whether by studying old mining maps of the region or by intuitively understanding the lay of the land. Now, he puts together his own expeditions, securing loans from the Council of Crânes to hire on Capricornes and procure equipment, leading his new crew out into the Pyrenees. He has <b>Resources and Network (+2)</b> when supported by a loan until they return to Perpignan, but if his endeavor fails he’ll need another way to pay his debts. Good luck.<br/><br/>In the meantime, he keeps up his communication with the Jehammedan tribes in the Pyrenean hills—while once it was a passing friendship, now it’s part of business. A few small nuggets of gold and silver as payment for his crew’s safe passage, along with news from Hybrispania and any other developments occurring in the area, so long as he doesn’t bother the Hagari. His <b>Network rises by (+2)</b>.<br/><b>EQUIPMENT:</b> Revolver; Mule; Notebook with exceptionally detailed mountain maps of the region`,

  'bordenoir-moniteur': 'Moniteur',
  'bordenoir-moniteurDescription': `<b>PREREQUISITE:</b> BOD+Toughness 6, AGI+Navigation 8, PSY+Reaction 6, Allies 3, Authority 1<br/><b>RESULT:</b> The Moniteurs each lead a squad of five Faucons, a tightly knit group patrolling the area around Perpignan. On the water he circles the fishing fleet in a well-armed speedboat, while on land he stands on the rear platform of a Kom acquired from the Africans. The cost of Petro is high, but the security and force projection it offers the Bordenoir’s enforcers is well worth it. Not to mention the terror a Moniteur inspires in his prey when the rattling of an engine is bearing down on them—the Bordenoir have no time for mercy, and their laws were built when it seemed the whole world was allied against them. Punishment is swift, and brutal.<br/><br/>While there is no love lost between the Bordenoir and the Neolibyan traders, the cunning Africans are easily able to recognise a situation that plays to their benefit—the Faucons and Moniteurs might only intend to protect their own Clan, but by extension they’re protecting the Neolibyans. As such, Moniteurs are showered with subsidies and gifts from the Africans; standard operating equipment and food is free for himself and his Faucons, he buys Petro at half price, and African Scrappers upgrade his vehicle at discount rates.<br/><b>EQUIPMENT:</b> Revolver; Speedboat or Kom; Grappling hook`,

  'bordenoir-colonel': 'Colonel',
  'bordenoir-colonelDescription': `<b>PREREQUISITE:</b> AGI+Projectiles 8, CHA+Negotiation 8, CHA+Leadership 8, Allies 4, Network 3<br/><b>RESULT:</b> Perpignan is divided up into a series of districts, each of them with one Bordenoir elected as its Colonel, their representative before the Council of the Crâne. He has to make sure he listens to his constituents, for otherwise he’ll be voted out at the end of his two-year tenure, but his authority gives him a <b>+2D to CHA+Negotiation</b> with the inhabitants of his district.<br/><br/>An extra four Colonels are chosen by the Crânes to oversee Scourger operations occurring in Perpignan’s sphere of influence, and ensure that the African warriors correctly adhere to the laws of the Bordenoir. While the Scourgers whine and complain about this restriction, the Neolibyans hold them back from any disobedience, not wishing to cause any upsets. The Scourgers acquiesce with a growl.<br/><b>EQUIPMENT:</b> Beret; Repeating rifle (hunting rifle)`,

  'bordenoir-poing': 'Poing',
  'bordenoir-poingDescription': `<b>PREREQUISITE:</b> BOD+Brawl 10, BOD+Force 8, AGI+Projectiles 10, CHA+Leadership 10, Allies 5, Renown 5<br/><b>RESULT:</b> When the Bordenoir were a scattered gathering of Clans, it took a single, heroic warrior to solidify their alliance and unite them in a single cause. The Poing carries that legacy, and only the most skilled and daring fighter in the Clan is chosen to rise to this rank. He constantly proves himself against the best of the best; taking down Kifo mercenaries, Apocalyptic brawlers, even sharks or buffaloes in melee combat—the more enemies he vanquishes, the more admiration and respect he receives from the Clan. Should war ever reach the shores of Perpignan, he will be the one to lead the Faucons into battle.<br/><b>EQUIPMENT:</b> Black gauntlet (knuckle duster); Shotgun; Gunboat with heavy MG`,

  'bordenoir-crane': 'Crâne',
  'bordenoir-craneDescription': `<b>PREREQUISITE:</b> CHA+Negotiation 10, CHA+Leadership 10, Allies 5, Renown 5<br/><b>RESULT:</b> Only those old and wise enough to be trusted with the full might of the Bordenoir are elected to the Council of Crânes, tasked with controlling the fate of the Clan and ensuring there is order within the city. In all negotiations they maintain balance, never openly favoring one Cult over another, always showing neutrality—although, of course, the Bordenoir come first. This has led to them becoming renowned in Franka as excellent mediators, and this has made them popular referees in every political matter in the region. All doors are open to the Crânes.<br/><b>EQUIPMENT:</b> Black and red sash; Rod of feathers; Seal of immunity; Legislative texts`
}

const resistanceClans = {
  resistance: 'Resistance',
  resistanceDescription: `The <b>Resistance</b> is a <b>Tech Level IV</b> Frankan Clan and nationalist movement centered in <b>Toulouse</b>, dedicated to uniting the scattered peoples of Franka, defeating the Pheromancers, and resurrecting the idea of a sovereign nation independent of domination by the great Cults. Its soldiers fight an exhausting war across multiple fronts, but every victory strengthens a growing mythology of sacrifice, brotherhood, and national rebirth that draws volunteers from villages and other Clans throughout the country. The Resistance deliberately cultivates memories of <b>Bygone France</b>: its Savants preserve books, relics, songs, histories, and military knowledge, teaching recruits that the land and its people are inseparable and that their struggle continues the legacy of generations who died defending Franka. Under <b>Maréchal de Franka Armand Malpierre</b>, the movement has increasingly evolved beyond a partisan army into the beginnings of an alternative government, establishing camps, logistics networks, intelligence operations, and civil administration across the country. Yet the Resistance remains dependent upon popular support, donations, trade, and cooperation with Cults such as the Spitalians, creating an uncomfortable contradiction for a movement whose ultimate ambition is complete self-determination. In essence, the Resistance is <b>Franka's emerging national army and revolutionary government</b>, attempting to turn countless independent communities into one people beneath the old tricolor.`
}

const resistanceRanks = {
  'resistance-cadet': 'Cadet',
  'resistance-cadetDescription': `<b>PREREQUISITE:</b> -<br/><b>RESULT:</b> Come one, come all. The only requirement to join the Resistance as a Cadet is that the applicant takes a vow on the spirit of Franka itself to set aside any other obligations for the duration of his service. Once the ceremony is complete, led by a Savant and spoken in an ancient dialect of the Frankan tongue, the new Resistance member can rise and join his new brothers and sisters in celebration. Training starts at 0600 tomorrow, don’t be late.<br/><br/>The fighters of the Resistance are held in high esteem in their domain. They get <b>+1D to all social interactions with the free Clans of Franka</b>. This bonus applies to all Resistance ranks.<br/><b>EQUIPMENT:</b> Tricolor badge; Field manual of the Resistance (+1D to INT+Legends concerning Franka, Pheromancers and drones)`,

  'resistance-chasseur': 'Chasseur',
  'resistance-chasseurDescription': `<b>PREREQUISITE:</b> AGI+Projectiles 6, INS+Survival 6<br/><b>RESULT:</b> He’s managed to make it through his first few excursions into the swamp, killed a couple of sickly drones expelled from their main hive, and proved to his instructors that he understands the basics. Good enough for now! The Cadet rises to Chasseur, and is attached to the main Resistance force. Now, he gets sent on missions deeper into Pheromancer territory, joining up with Spitalian strike teams to assault spore fields and Aberrant-controlled villages.<br/><br/>His training never stops, however; knowledge is survival out in the swamp, and he studies hard. Behavioral studies, field reports, dissection records, all of it is used by the Resistance to equip their soldiers with the understanding of how to bring down their enemies: the Chasseur adds <b>+1D to all Attack rolls against Pheromancers and drones</b>.<br/><br/>Chasseurs have free access to inns and hostels in the cities of Franka, where they are cheered and celebrated as the heroes of the people. They do not have to work, and instead are supported and fed for free everywhere in Franka.<br/><b>EQUIPMENT:</b> Hunting rifle with bayonet`,

  'resistance-gendarme': 'Gendarme',
  'resistance-gendarmeDescription': `<b>PREREQUISITE:</b> AGI+Projectiles 6, Authority 2<br/><b>RESULT:</b> Everyone knows that true glory is found out in the deep forests, crawling through knee-deep swamp muck to slaughter the forces of the enemy. However, just as essential is the work of the Gendarmes back home. They are tasked with maintaining order in the settlements and war camps of the Resistance, functioning as both a logistical division and a military police force. They ensure that supplies are passed out to the Chasseurs, that ammunition is distributed properly, and that the Resistance’s soldiers are behaving correctly—they can’t win over the hearts and minds of the free peoples of Franka if they present themselves as uncultured ruffians. Additionally, the Gendarmes organize the cooperative efforts with the Spitalians, and add <b>+1D to rolls when negotiating with the Cult of Doctors</b>.<br/><b>EQUIPMENT:</b> Uniform; Light pistol`,

  'resistance-commandant': 'Commandant',
  'resistance-commandantDescription': `<b>PREREQUISITE:</b> AGI+Projectiles 7, CHA+Leadership 7, INS+Survival 7, Renown 3<br/><b>RESULT:</b> He’s proven himself under fire, led squads of Chasseurs charging headfirst into the fray, and—most importantly—he isn’t dead yet. All of these are the mark of a special talent, someone who can be relied upon and trusted with more responsibility in the war against Franka’s oppressors. The Commandant’s <b>Allies and Authority Backgrounds are raised by (+1)</b>, and he can apply his Resources to the Spitalians at a penalty of <b>(-2)</b>.<br/><br/>With his new station comes a new set of privileges. He no longer needs to scrounge up his own possessions and wind his way through the bureaucracy of the Savants to obtain equipment, instead he takes whatever he needs in the name of the Resistance’s fight—let the worrywarts in Toulouse handle the fallout, he has a war to win. He can draft reservists from the population, can confiscate food and weapons for his soldiers, and can dispense martial justice: he is at liberty to execute criminals on the spot, even without a time-wasting trial and formal verdict.<br/><b>EQUIPMENT:</b> Uniform; Pistol; Grenades (smoke, ozone, fungicide)`,

  'resistance-savant': 'Savant',
  'resistance-savantDescription': `<b>PREREQUISITE:</b> INT+Legends 8, CHA+Expression 8, Authority 3<br/><b>RESULT:</b> The Chasseurs and Commandants fight to make Franka a proud nation once again, but the Savants fight to ensure the people remember the proud nation it once was. As archivists they work to keep expanding the Resistance’s foundation: the people need something to fight for, and the Savants provide just that. They categorize and document the artifacts of Franka’s past recovered during campaigns, trade with Scrappers and explorers for precious tidbits, and occasionally lead their own expeditions into the swamps to hunt down especially significant items. These are brought back to the cities on the coast, where the Savants showcase the glorious creations of Frankans long gone, reminding the population of their illustrious heritage and forcing them to confront the reality of their present situation. Whenever Franka, its culture, or its history are concerned, the Savant adds <b>+1D to all INT Action rolls</b>.<br/><br/>Additionally, the Savants take up the role of civil servants for the people, handling administrative duties and ensuring the cogwheels of their military continue to function.<br/><b>EQUIPMENT:</b> Seal of the Resistance (to bear witness for agreements and decrees)`,

  'resistance-général': 'Général',
  'resistance-généralDescription': `<b>PREREQUISITE:</b> BOD+Melee 7, AGI+Projectiles 8, CHA+Leadership 9, INT+Legends 7, Authority 4, Renown 4<br/><b>RESULT:</b> A Général’s Renown attracts Cadets. He is a hero amongst heroes, the figurehead of a new era. His personal acts of resistance inspire the people of Franka to follow in his footsteps. Wherever he gives a speech, people listen. If the Général actively looks for new recruits, his Renown decides how many fighters he can win for the Resistance after a week of beating the drum: <b>Renown × 1D</b>. Thus, in just a few short months the Général can mobilize entire regions to follow him into battle. At Renown (0), however, his force is plagued with deserters and cowards—one Cadet abandons the cause per week, instead.<br/><br/>Spitalians have no command over a Général. They suffer an automatic penalty of <b>-1D</b> to any rolls trying to exert their authority while negotiating with him. In and around the city of Toulouse, where the Général’s influence and fame is at its highest peak, this penalty rises to <b>-3D</b>.<br/><b>EQUIPMENT:</b> Uniform; Officer’s coat and saber; Assault rifle`,

  'resistance-maréchal': 'Maréchal',
  'resistance-maréchalDescription': `<b>PREREQUISITE:</b> BOD+Melee 8, AGI+Projectiles 8, CHA+Leadership 10, CHA+Negotiation 9, INT+Legends 10, Authority 5, Renown 6; Armand Malpierre must yield<br/><b>RESULT:</b> The Maréchal de Franka is the supreme commander of the entire Resistance. He is the mastermind behind every troop movement and campaign, and he usually plans several generations ahead. To his soldiers, his word is absolute—beyond the mere shackles of the chain of command, his voice rings out with the might of all of Franka behind it. He appoints Générals to lead his forces, negotiates with the rulers of cities to accommodate his men, and coordinates eye-to-eye with the Cults. His <b>Allies Background can never fall below (6)</b>.<br/><br/>For the Maréchal, there can only ever be a single goal. Liberating Franka from all the chains holding it down, the Pheromancers, the invaders, the Cults. He will stop at nothing, and sacrifice anything, to achieve it.<br/><b>EQUIPMENT:</b> Anything and everything the Resistance can provide`,

  'resistance-grandSavant': 'Grand Savant',
  'resistance-grandSavantDescription': `<b>PREREQUISITE:</b> INT+Legends 12, CHA+Conduct 10, CHA+Expression 10, CHA+Negotiation 10, Renown 6; Pélat du Casse must yield<br/><b>RESULT:</b> Maréchal and Grand Savant work hand in hand. On the surface, the Grand Savant is the domestic ruler of the Capitol in Toulouse, negotiating and managing the civil matters required to maintain the Resistance’s headquarters. He ensures that the food keeps flowing, the raw materials keep coming in through donations, and even bites his tongue and reaches out to powerful Neolibyans. The Grand Savant also organizes and leads the Savants; no one knows the history of what Franka used to be more than him.<br/><br/>Look deeper, though, and the true nature of the position is revealed. The Grand Savant is the Resistance’s spymaster, coordinating the infiltrators and contacts spread throughout Franka—more widely spread than the Cults would like. His <b>Secrets Background can never fall below (6)</b>.<br/><b>EQUIPMENT:</b> Seal of the city of Toulouse; Keys to the Capitol; Register of all Savants`
}

const resistancePotentials = {
  brotherhood: 'Brotherhood',
  brotherhoodDescription: `<b>PREREQUISITE:</b> -<br/><br/><b>RESULT:</b> As a Resistance fighter charges across an open space towards his enemy, side by side with his comrades in arms, he adds <b>+1D per Potential Level to all Attack rolls made during the assault</b>. The bonus ends as the enemy closes into close quarters, the brotherhood descending into a mad frenzy of melee.`
}

const pneumancersClans = {
  pneumancers: 'Pneumancers',
  pneumancersDescription: `The <b>Pneumancers</b> are the heavily armed inhabitants of <b>Nullpellia</b>, originally created as the warrior caste of the Mechans and subjected for generations to exploitation, humiliation, and manipulation by their supposed masters. During the catastrophic struggle for Nullpellia they finally revolted, slaughtered the Mechans' priestly rulers, destroyed the symbols of their oppression, and claimed the ruined Cauldron City for themselves. Rather than abandoning the Mechanist's legacy, the Pneumancers came to believe that <b>they—not the Mechans—are his rightful heirs</b>, reviving his original ideal that everyone deserves food, a place within the community, and meaningful work. Their society remains deeply militarized because warfare is what generations of Pneumancers were bred and trained to understand, and Nullpellia is defended by formidable <b>steam-powered technology, bolt weapons, fortifications, and heavy cannons</b>. Political freedom has consequently proved almost as difficult for them as winning it: outsiders, Scrappers, Apocalyptics, neighboring Clans, and the Protectorate all compete for influence while the Pneumancers struggle to determine what kind of society they actually want to build.`
}

const pneumancersRanks = {
  'pneumancers-picker': 'Picker',
  'pneumancers-pickerDescription': `<b>PREREQUISITE:</b> -<br/><b>RESULT:</b> The first lesson in life is pain. The second, how to endure it. Every day they are led to the hot plate already sizzling in the center of the training chamber. They are lined up on one side, and on the other a door is opened leading to the mess hall. Time to act.<br/><br/>The agonizing event burns itself into their minds, but they will overcome their fear. A child will only receive food if they repeatedly touch the plate week after week until all fear of fire is purged from their soul. Then, they may advance. By the time they reach adulthood the Pneumancer warriors have trained in this way enough to push through the most painful injuries, and <b>ignore up to -3D of Trauma penalties</b>.<br/><br/>Pickers are yet to do enough to even consider being worthy of a name, and fulfill only idle roles in the Pneumancer society. They are the nameless, faceless underlayer of the Clan.<br/><b>EQUIPMENT:</b> A mask, which will become their surrogate face for the years it takes to earn the right to use their own`,

  'pneumancers-smogger': 'Smogger',
  'pneumancers-smoggerDescription': `<b>PREREQUISITE:</b> BOD+Force 6, BOD+Athletics 4<br/><b>RESULT:</b> Check the barometers, refeed the conveyors. Good. Pressure building up in section 3-43. Release the valves, pump the steam, then clean up the main turbine. The Smogger knows every section of the Cauldron City by heart, and he knows that every engine requires its fuel. The monstrous boilers nestled beneath the city guzzle coal like a colossal beast devouring black, soot-coated nuggets of meat, and the Smogger is part of the workforce to keep it well-fed. He works in the sprawling coal mines buried deep beneath the surface, untapped since the Bygone days, shoveling the city’s lifeblood into carts and dragging it back to where it is needed.<br/><br/>Smoggers are far from just mere miners, however. When the Pneumancers go to war, they are called up from their claustrophobic mineshafts to supply the Clan’s siege engines, along with providing fresh ammunition for the Boilers and their Pneumo Hammers.<br/><b>EQUIPMENT:</b> Pickaxe; Coal sack; Slicer; Mask modified with dedicated filters for coal dust`,

  'pneumancers-boiler': 'Boiler',
  'pneumancers-boilerDescription': `<b>PREREQUISITE:</b> AGI+Projectiles 7, BOD+Toughness 6<br/><b>RESULT:</b> Boilers are the core of the Pneumancer host. Once, they were the frontline warriors thrown into conflicts across the Ramein region. They trained hard, and fought harder, all for the promise of a glimpse of freedom. The warriors of those days passed their ideals to the next generation, who continue to carry that fighting spirit on in their hearts. One problem—what are they supposed to do with no war to fight?<br/><br/>Nowadays, a Boiler’s life is far more complex. He works in Nullpellia as a ground trooper for the Pneumancer armies. Farther from home he ventures out to collect tribute from villages under Nullpellia’s aegis, or offers himself up for hire in countryside militias across Ramein and beyond to protect against overeager Scrappers, pestering Cockroaches, poaching Phosphorites, or reckless adventurers of all kinds. It’s a far cry from the glorious days of yore, but it’s a start.<br/><b>EQUIPMENT:</b> Pneumo Hammer; Free access to coal and bolts for ammunition`,

  'pneumancers-assembler': 'Assembler',
  'pneumancers-assemblerDescription': `<b>PREREQUISITE:</b> AGI+Crafting 8, INT+Engineering 7, INT+Legends 7<br/><b>RESULT:</b> The Assembler works alongside the Warcrafter, cracking ancient blueprints containing hints of the Mechanist’s grand designs and building the machines that keep Nullpellia running, whether on the battlefield or in the Cauldron City. He is constrained by the limitations of the Clan’s technological understanding, forced to use steam-based substitutes in place of many of the advanced electrical systems present in the Mechanist’s works, but constraints are the mother of invention.<br/><br/>Assemblers are the most open-minded of the Pneumancers, and actively search for contact with Scrappers and Chroniclers, trading tidbits of information from the Mechanist’s teachings for electrical components or lessons in circuit design. Inch by inch, the Pneumancers are clawing their way from the technological lull the Mechans condemned them to, and rising to become the true heirs to the Mechanist.<br/><b>EQUIPMENT:</b> The right to remove his mask and take a name; Assembler’s tools (+1D to AGI+Crafting and INT+Engineering); Right of first refusal on any scrap or artifact from the Depths`,

  'pneumancers-rigger': 'Rigger',
  'pneumancers-riggerDescription': `<b>PREREQUISITE:</b> AGI+Projectiles 8, AGI+Navigation 6, INT+Engineering 5, Authority 2<br/><b>RESULT:</b> The Pneumancers have grown up in a land of technological wonder far beyond anything anyone alive in the world today has ever seen, passed onto them by the Mechanist himself. The Rigger doesn’t understand how to design the varied siege engines and sophisticated machinery of Nullpellia, but he’s damn good at operating them. He is tasked with resetting the border defenses and traps, leading squads of Boilers out to patrol the limits of their current territory, along with piloting the Pneumancer weapons of war.<br/><br/>Due to their duties out on the edge of Nullpellian territory, it’s the Riggers who come into contact with the Cults of Borca and elsewhere the most, and as such they are tasked with listening to the stories of the world beyond Ramein, the political events, wartime gossip, anything and everything they can take in, and bringing it back to the city to ensure the Heralds can keep an up-to-date view of the world around them. Sometimes, Riggers are even hired out as bodyguards or mercenaries to travelers and trade caravans passing through Borca.<br/><b>EQUIPMENT:</b> The right to remove his mask and take a name; Option to use a Pneumo Cannon or Thundermaul in battle, unless assigned to operate a siege weapon`,

  'pneumancers-herald': 'Herald',
  'pneumancers-heraldDescription': `<b>PREREQUISITE:</b> CHA+Expression 8, CHA+Negotiation 6, INT+Legends 9, Network 3<br/><b>RESULT:</b> The Heralds originally emerged from the faceless masses of Pneumancers in the depths of the Cauldron City as lorekeepers, distinguishing themselves with their oratory skills. They rekindled the stories of heroes past, ensuring they would not be forgotten as the generations crept onwards. They recounted the tales of the Mechanist and his divine wisdom, and began to form rituals in his honor. Now that the Clan has clawed its way to freedom, the Heralds must take on a very different role—one for which they are not nearly as equipped.<br/><br/>There are dozens of Clans and Cults, large and small, that the Pneumancers must now interact with directly. It is the Herald’s task to venture out and facilitate these interactions, making friends and soothing enemies. Additionally, they have expanded their role as the keepers of the past, many finding work in the temples of the New Dawn as priests in honor of the Mechanist’s legacy.<br/><b>EQUIPMENT:</b> Official Pneumancer medallion (If visibly displayed, First Impression (+1D)); Free access to the Mechanist’s tablets for examination and study`,

  'pneumancers-warcrafter': 'Warcrafter',
  'pneumancers-warcrafterDescription': `<b>PREREQUISITE:</b> Public demonstration of exceptional engineering work; INT+Engineering 10, INT+Science 9<br/><b>RESULT:</b> The ingenuity of the Mechanist is mythical, tales of his deeds and creations spreading far beyond the Nullpellian territory to filter through Scrapper halls and taprooms as legendary stories. For the Pneumancers, these are more than just mere yarn and fables. They believe that the skill and creativity of their city’s founder passes directly through their ranks, generation after generation. The Warcrafter inherits his talent for design and engineering, and is tasked with creating the Clan’s most brutal and effective weapons of war.<br/><br/>The current Warcrafter, Deus Volt, rose to prominence by laying down the plans for extensive upgrades to Nullpellia’s Toll, a siege weapon designed to break through even the thickest gates based on an upscaled version of the original Pneumo Hammer designs, the Mechanist’s roller carriage allowing the massive bolt hammer of the weapon to move smoothly in its track.<br/><br/>As a Warcrafter, Deus Volt has access to the treasure chamber of the temple of the New Dawn, where he can study every recovered blueprint of the Mechanist with his own eyes, and examine every piece of equipment plundered from the Mechans during the uprising.<br/><b>EQUIPMENT:</b> Full cooperation of the Assemblers should he wish to have one of his designs built; Cogwheel key to the hidden armory beneath the Firewall, containing a preserved store of Bygone munitions, for emergencies`,

  'pneumancers-engine': 'Engine',
  'pneumancers-engineDescription': `<b>PREREQUISITE:</b> Katechan must pass away—he will not step down; CHA+Leadership 11, PSY+Domination 10<br/><b>RESULT:</b> The Pneumancers are a terrifyingly powerful force, well trained and fearless, but when the Cauldron City gates were first blown open, they were frozen. They needed an impetus to set themselves into motion, driving them towards their freedom. They needed an Engine. Katechan the Liberator took that role, leading the first attack squads onto the surface and into battle with the Phosphorites, and it was a natural choice for him to continue his path after the conflict settled.<br/><br/>Katechan is the rock-hard iron core of his Clan, and his willpower and strength is the driving force behind its actions. His word is backed with experience and heroic deeds taught to every one of the Pickers in the Cauldron City, and his every proclamation ripples through the ranks. When the Engine commands, the Pneumancers act.<br/><b>EQUIPMENT:</b> The Engine has unlimited access to the weapons storage of the Pneumancers, and can requisition any and all of the Clan’s equipment in times of war. His Resources Background is permanently set to (6)`
}

const pneumancersPotentials = {
  throughAdversity: 'Through Adversity',
  throughAdversityDescription: `<b>PREREQUISITE:</b> -<br/><br/><b>RESULT:</b> The Pneumancers view all resistance as character forming, and shine brightest when they are overcoming the odds through sheer force of will and tenacity. When a Pneumancer succeeds on a roll which was affected by negative penalties, he regains a number of <b>Ego Points equal to the dice penalty</b>, up to a maximum value of the Potential Level.`,
  apnea: 'Apnea',
  apneaDescription: `<b>PREREQUISITE:</b> BOD+Stamina 6<br/><br/><b>RESULT:</b> Through murderous training sessions in the Smog Chambers, where every breath threatens to combust the lungs, the Pneumancer’s diaphragm has adapted to extended periods of held breath. Utilizing enhanced internal breathing patterns, along with the proper mental fortitude to push through the pain of aching lungs and the panic-inducing effects of suffocation, they can hold their breaths for a number of minutes equal to their <b>Stamina Skill per Potential Level</b>, unless they take more than their Stamina Skill in Damage and are forced to exhale.`
}
