const exaltersClans = {
  exalters: 'Exalters',
  exaltersDescription: `The <b>Exalters</b> are the scattered descendants of the once-mighty city-state of <b>Exalt</b>, an extraordinarily advanced Borcan civilization whose philosophy of <b>Free Spirit</b> emphasized individual potential, intellectual experimentation, self-determination, and a society in which people naturally found the roles best suited to them rather than submitting to conventional hierarchy. At the heart of their civilization lay the mysterious <b>Grindworks</b>, a subterranean complex capable of analyzing and even altering human psychological Concepts through a process known as <b>embossing</b>, allowing carefully assembled groups called <b>Constellations</b> to function with remarkable synergy. Exalt's success eventually curdled into ideological extremism and conflict, and after its fall the Judges—with assistance from the Spitalians and Chroniclers—systematically erased its culture, destroyed its monuments, persecuted its survivors, and drove the remaining Exalters into exile around <b>Liqua</b>. More than a century later, the Clan survives as a fragmented shadow of its former glory, ranging from roughly <b>Tech Level III to V</b>, secretly gathering lost descendants, preserving the humanitarian ideals of Exalt, and sending dangerous expeditions through hostile territory to reclaim the Grindworks. Vigils seek scattered bloodlines, Zodiacs assemble new Constellations, Ariadnes navigate the ancient complex, and the Clan dreams ultimately of returning home and restoring Exalt. In essence, the Exalters are <b>the dispossessed heirs of a fallen utopian superpower</b>—brilliant, proud, increasingly desperate, and convinced that humanity once possessed a better way of organizing itself that only they can resurrect.`
}

const exaltersRanks = {
  'exalters-imperfect': 'Imperfect',
  'exalters-imperfectDescription': `<b>PREREQUISITE:</b> -<br/><b>RESULT:</b> Imperfection is a stain. Everyone is born with it. The Grindworks once alleviated this terminal flaw through the process of embossing, and guided the Exalters towards the peak of human capacity. No longer. Today, the Clan is riddled with Imperfects, in fact, the vast majority of Exalters are nothing but a shadow of their former self, having never experienced the powers bestowed by the Grindworks, nor undergone the mind-altering modifications of the Basalt Plain.<br/><br/>Unless an Imperfect is chosen to travel to Exalt and fulfil their destiny, they can only advance through the regular hierarchy established in the Liquan exclave, rising in the chain of command and recognized by their personal accomplishments yet always frowned upon as second rate examples of their role—a faint approximation of a true Exalter.<br/><b>EQUIPMENT:</b> A gilded token bearing Exalt’s symbol, to identify their allegiance to other members of their Clan; Can only access equipment up to Tech III`,

  'exalters-solemn': 'Solemn',
  'exalters-solemnDescription': `<b>PREREQUISITE:</b> INT+Legends 8, INS+Empathy 7, Secrets 3<br/><b>RESULT:</b> The Exaltian paradigm must survive, and it is the Solemn who carries the torch of remembrance. Acting as secretive priest of the humanitarian imperative, Solemns travel the world, spreading the seed of Exalt’s ideology in hopes of reigniting the Clan’s former strength of cultural domination. Theirs is a mental conquest that puts them at odds with established power structures, and it is for that reason that they must act alone.<br/><br/>Solemns excel at infiltrating advisory positions in politically opposing enclaves and support contrarian viewpoints, slowly building up radical counter-movements by converting groups of people who fall under their administration. Therefore they make excellent ambassadors deployed by the Clan who can upset the rigid dynamics of hereditary enemies and cause friction across their domain of influence. But the Solemn must act with utmost care, otherwise their head will end up on the chopping block.<br/><b>EQUIPMENT:</b> Solemns require money for bribery and manipulation. They receive (+3) Resources which they can spend freely to achieve their current milestone. However, each failure reduces the Bonus by (-1). If it drops to (0) the Solemn is called back to Liqua for readjustments.`,

  'exalters-benign': 'Benign',
  'exalters-benignDescription': `<b>PREREQUISITE:</b> INT+Medicine 6, INT+Engineering 6<br/><b>RESULT:</b> The core philosophy of the Exalters recognizes no difference between the human elements of the empire and the equipment, material, and constructions that make up its infrastructure. All of the pieces of the grand puzzle have their own blemishes, conditions, and breaking points, the only difference is whether blood or oil flows through them. After all, just as an engine can be sent into a workshop, so too can a person be sent down into the Grindworks and return as an improved, refocused version of themselves. It’s all the same, in the end.<br/><br/>As such, the Benigns turn their skills towards the construction and repair of all machinery, organic or technological. They are the surgeons stitching Exalt’s warriors back together after a battle, just as much as they are the engineers piecing together advanced weapons of war. Whether holding a red-hot cauterizing rod or a white-hot welding torch, the Benign is right at home.<br/><b>EQUIPMENT:</b> Medical and technical tools (+2D to INT+Medicine or INT+Engineering); Pattern Weaver`,

  'exalters-vigil': 'Vigil',
  'exalters-vigilDescription': `<b>PREREQUISITE:</b> CHA+Expression 6, Any Combat Skill 6<br/><b>RESULT:</b> The trajectory of glorious success has been shattered, the Constellations have splintered, and the Clan was dispersed across the face of the Earth, washing ashore in remote areas with no means of finding the way back. Now the Vigils must set out from Liqua and travel the countryside in search of the scattered branches of the bloodline; only when all of the lost members are once again connected, will the reborn empire flourish.<br/><br/>The Vigils must also guide Exalters chosen for the embossing through the Clan infested territories beyond the borders of Siege. Their role as guardians never ends, and a Vigil must stand to his last dying breath to ensure the safety of his people. His conviction is crucial. Whenever he must safeguard other Exalters, he regains <b>(3) Ego Points</b> as the memetics laced into his brain jolt him with determination. Additionally, when he acts on behalf of Exalt and in its defense, his <b>Resources and Authority Backgrounds rise to (4)</b> until the threat has passed.<br/><b>EQUIPMENT:</b> Pasiphae’s Stride; Sword engraved with the glyph of Revenge; Type-97 Rifle; Exalter battle armor (Armor rating 3, Enc. 1); Frag Grenades`,

  'exalters-ariadne': 'Ariadne',
  'exalters-ariadneDescription': `<b>PREREQUISITE:</b> BOD+Force 6, BOD+Athletics 4<br/><b>RESULT:</b> Even before he ever laid eyes on the mystical pathway, he had studied all of the existing legends passed down by those who came before, lived vicariously through their countless journeys into the Grindworks, and was instructed through rigorous training at the hands of Enceph’s Halos how to survive in the dangerous environment beneath the surface. When the time comes for him to make the trek across the hostile terrain standing between himself and Exalt, he will be ready to descend into the Pathways and take his place in his destined home.<br/><br/>In critical situations, such as when a Constellation must be assembled for a desperate mission, the Ariadne takes on a different task. He descends into the Basalt Plain once again, but not to be embossed. It is the Ariadne’s duty to escort someone else through the obstacle course towards their destination; in this fashion, the chosen Exalter will have a weaker affiliation with the Concept of choice, but it’s better than risking death in the tumultuous forest of pylons below. Meanwhile, the Ariadne has his own problems to deal with—the augmented systems don’t recognize the unexpected presence, and attempt to wipe it out.<br/><b>EQUIPMENT:</b> Recreated map of Exalt and calibrated compass, including notes on the Pathways (+3D to INS+Orienteering in the ruined city); Delver’s Crest`,

  'exalters-imperative': 'Imperative',
  'exalters-imperativeDescription': `<b>PREREQUISITE:</b> CHA+Leadership 8, PSY+Cunning 8<br/><b>RESULT:</b> In the truly egalitarian society of Free Spirit, there was no room for archaic hierarchies, only voluntary responsibility. With the changing of the seasons and the monumental fall of the Exaltian paradigm, the survivors had to resort to the concept of leadership, manifesting itself in the role of the Imperative. They must act to keep their people united without the benefit of being able to rely on the unifying principles of the Grindworks. A difficult task, one the Imperatives must handle with grace and understanding, balancing the needs of the individual against the needs of the Clan in all worldly affairs.<br/><br/>The problems are ubiquitous. Too many variables cloud all clear thought. Even so, the Imperatives must rise above and declare the best course of action, or they will only prolong the suffering of their people. Any decision is better than stasis.<br/><b>EQUIPMENT:</b> Hexagonal seal of authority, black on one side and gold on the other (+1D CHA+Leadership against other Exalters); Hierarch`,

  'exalters-zodiac': 'Zodiac',
  'exalters-zodiacDescription': `<b>PREREQUISITE:</b> INS+Empathy 10, PSY+Cunning 9, Authority 5, Secrets 5<br/><b>RESULT:</b> In a time long forgotten, Constellations naturally arose from the ranks of the Exalters. No fatherly advice was needed, no overseeing figure, it was simply a consequence of life. Today, the Grindworks is almost inaccessible, and the simple, hands-off approach is no longer viable. Not all Constellations can rely on the luxury of having their Concepts shifted and altered to suit the optimal configuration, and the few that do must immediately be thrown into the fire and tested in dangerous circumstances. For once in their great history, the Exalters now have to be selective and elitist towards their own.<br/><br/>It is the task of the Zodiac to determine who amongst his people is suitable for embossing, who will do the most good when their Concept is re-aligned. They assemble expeditionary groups to Exalt, assign duties, and provide instructions as to which Alignment is required to propel the Clan onwards. Alongside that, though, the Zodiac also traces out whatever Constellations he can using the resources available to him; instead of molding others to form the perfect grouping, he must simply choose the right individuals to meld together. It’s an imperfect solution for an Imperfect people, but for now there’s no other option.<br/><b>EQUIPMENT:</b> Old texts passed down from previous Zodiacs granting them the Potential Memetic Teachings 1, and giving +2D to attempts to discern an Exalter’s Concept`,

  'exalters-concordant': 'Concordant',
  'exalters-concordantDescription': `<b>PREREQUISITE:</b> Apex; Chosen by Exalt<br/><b>RESULT:</b> The common person is defined by their Concept, a given set of characteristics determining every facet of their response to outward stimuli. The Concordant, however, has been chosen by the Benevolent Spirit of Exalt to emerge as something altogether more profound. He becomes the embodiment of a chosen Alignment, carrying all of its Concepts in Affinity within himself, able to switch between the varied structures of his personality at a whim. At a moment’s notice, he can shuck the limitations of one mindset as easily as changing clothes, shedding any memetic shackles that have been placed on him without having to resort to the cleansing effects of the Grindworks.<br/><br/>Concordants are known as avatars of Revenge, Ambition, or Destiny, forever trapped within the confines of their Alignment, yet uniting all aspects of a Constellation within a single soul. There is no way back for them once the metamorphosis is completed, and such divinity comes with a price. With every shift of his personality the Concordant loses the fetters of his former self, as he closes in on a transhuman state of being. He can’t regain Ego Points via any of his Concepts, as none of them are dominant anymore. Battered by conflicting thoughts of a multitude of identities struggling for control, he will only regain Ego by following the purpose of his Alignment. The Concordant automatically gains the respective Constellation bonus for his Alignment.<br/><b>EQUIPMENT:</b> KEReS; Ancev; Seal allowing the Concordant to call up to 6 Vigils to his side in pursuit of his Alignment.`
}

const exaltersPotentials = {
  formerGlory: 'Former Glory',
  formerGloryDescription: `<b>PREREQUISITE:</b> Exalters<br/><br/>Cultrin and the rise of Exalt may seem like a distant memory to some. To others, it is a birthright. The old traditions survived with the Exalters who fled and spread among the many cities of the Protectorate. Cultrin’s doctrine lives on...<br/><br/><b>RESULT:</b> It takes tremendous willpower to stay true to Exalt’s ideals, a hundred years after its fall. Is it the only reason for the extraordinary resilience of the Exalters’ mind? The character adds <b>+1D per Potential Level to Mental Defense rolls</b>. If the attack is based on memetics, he adds <b>(1) Trigger per Potential Level</b> instead.`,

  theApex: 'The Apex',
  theApexDescription: `<b>PREREQUISITE:</b> INT+Focus or INS+Primal 10; Both of the chosen Concept’s defined Skill Bonuses to an Action Number greater than 8; Embossed<br/><br/>In the golden age, the Exalters had no need for the rigid, well-defined rank structures that characterized many of the Cults and Clans of the world. Instead, they achieved the ultimate goal of the Free Spirit program—a flat, shifting hierarchy where everyone naturally settled into the role that best suited them, a people united by their individuality, never submitting to another based on the intangible concept of “authority.” With the Grindworks out of reach, though, this potential was lost, and it became clear that the Exalters would need structure to survive. Even so, they didn’t lose track of their once-great nature. They remembered the Apex.<br/><br/><b>RESULT:</b> To become an Apex, the Exalter must shed the rigid mindset of hierarchy and understand the true nature of being a Free Spirited individual, a state which can only be achieved after many successful embossings in the Grindworks. His <b>Allies, Authority, and Resources Backgrounds rise to (4)</b> and cannot decrease below this point, and he has <b>+2D to all interactions with his own people</b>. Additionally, due to his new mindset brought on by dozens of Conceptual shifts or many experiences in a variety of Constellations, he can easily merge with any Alignment—even if he isn’t fully in Affinity. Whenever an Apex joins a group following any Alignment, he does not contribute or receive Aversion penalties, even if his Concept is in Aversion. However, he additionally does not contribute to Affinity bonuses.`
}