const sanglierClans = {
  sanglier: 'Sanglier',
  sanglierDescription: `The <b>Sanglier</b> are a <b>Tech Level IV</b> Clan ruling <b>Montpellier</b> whose entire society is built around the belief that their bloodline represents the purified inheritance of old Franka. Organized around <b>seventeen ancient Houses</b>, they practice carefully controlled marriage and reproduction, with bloodlines meticulously recorded and promising outsiders sometimes incorporated to strengthen the Clan; their leaders, the <b>Cerveau</b> and <b>Neurone</b>, effectively cultivate the population as though maintaining an enormous genealogical garden. The Sanglier believe that generations of selective breeding will eventually produce the <b>true king of a reborn Franka</b>, and their obsession with hereditary excellence is reinforced through elaborate blood rituals and a rigid hierarchy of legionaries, family leaders, and political schemers. Intelligent, educated, technologically capable, and highly ambitious, they readily absorb useful knowledge from Spitalians, Neolibyans, and other Cults without surrendering their own identity, although a growing number of younger Sanglier are rejecting the elders' control and leaving Montpellier to join the Resistance. In essence, the Sanglier are <b>Franka's eugenicist aristocracy</b>—cultured, capable, fanatically proud of their ancestry, and convinced that humanity's future monarch will eventually emerge from their carefully cultivated blood.`
}

const sanglierRanks = {
  'sanglier-baisse': 'Baisse',
  'sanglier-baisseDescription': `<b>PREREQUISITE:</b> -<br/><b>RESULT:</b> He either hasn’t grown old enough to be useful, or has just recently been introduced to the Clan by a Veine—in the eyes of the Ventricules, they are the same. He carries out menial tasks and performs services for his betters until he manages to prove his worth. Otherwise, he’ll find a place in the legion.<br/><b>EQUIPMENT:</b> -`,

  'sanglier-sang': 'Sang',
  'sanglier-sangDescription': `<b>PREREQUISITE:</b> BOD+Toughness 6, AGI+Projectiles 6<br/><b>RESULT:</b> The world is diseased, infested and infected with parasites and viruses alike. Pheromancers stalk the swamps north of Montpellier stealing people’s souls while criminals strike from dugouts and hideaways hidden in the trees, and it’s the task of the Sanglier legion to function as an immune system, root these impurities out, and exterminate them.<br/><br/>In the legion, the 17 families of the Clan are dissolved and cast aside, at least when on duty. The legionnaires are brothers in arms: that’s the only relation they can rely on when an Expatriate and its drone horde is bearing down on them. For the duration of their service, they eat, sleep, and train with their comrades until each squad is a well-oiled machine. They particularly focus on piercing strikes, lancing like a scalpel into vulnerable areas—both on a strategic level, finding the weak spots of distribution networks or smuggling gangs, and on the tactical level, prioritising carefully considered and accurate blows. They add <b>+1D to Aimed Attacks</b>.<br/><br/>The red capes of the legionnaires are well known far beyond the borders of Montpellier. Anyone causing trouble in the Rhône Delta will eventually come face to face with the Sang, and find that they are far from squeamish. As an experienced militia they are both feared by and popular with the people for their deeds: <b>Authority (+1), Renown (+1)</b>.<br/><b>EQUIPMENT:</b> Red cape; Short sword; Hunting rifle`,

  'sanglier-veine': 'Veine',
  'sanglier-veineDescription': `<b>PREREQUISITE:</b> CHA+Seduction 6, PSY+Cunning 6, Network 1; Scion of one of the 17 houses of the Sanglier<br/><b>RESULT:</b> The Sanglier are proud of their heritage and the purity that they have maintained throughout the tumultuous history of their region, but they are fully aware that the 17 houses would descend into wretched savagery and deformity if they never bred outside of their own family tree. The Veine’s blood is strong and pure, and she knows it. It is her task to find new recruits for the Clan, those who are of good stock and who will be of use to the Sanglier.<br/><br/>Should the Veine introduce a promising newcomer to the Clan, one with similarly promising blood who quickly demonstrates his usefulness and respect for the traditions he has now been inducted into, she gains <b>Allies (+1)</b>. If, however, her chosen recruit is discovered to be feeble or weak in spirit, her Allies drops by <b>(-2)</b>.<br/><br/>In Montpellier, Veines also find work as medicine women, using their Clan’s extensive knowledge of biology to their benefit. While traumatic injuries and battle wounds are best taken to the Spitalians, the Sanglier healers can determine far more subtle upsets; by tasting a single drop of blood, a Veine can diagnose hormone imbalances, dietary deficiencies, or even more insidious illnesses that would be missed by the common Famulancer.<br/><b>EQUIPMENT:</b> Hematite necklace; Scented oils; Recipes for blood rituals (regenerate (2) Ego, once per day)`,

  'sanglier-os': 'Os',
  'sanglier-osDescription': `<b>PREREQUISITE:</b> AGI+Projectiles 8, CHA+Leadership 6, PSY+Faith/Willpower 6, Authority 2, Renown 2<br/><b>RESULT:</b> The swamps are a dangerous place, and survival is no easy feat. As such, the truly skilled amongst the Sanglier legion are quickly distinguished and elevated to the rank of Os—it is now their task to train and lead other new legionnaires into combat. An Os is responsible for <b>(3 × Authority) Sang legionnaires</b>, and their deeds reflect back on him. Once per day, the Os can inspire his troops and allow them to regain <b>(2) Ego</b>.<br/><br/>An Os and his Sang can freely use Spitalian camps and get the best medicine, food, and lodging. During expeditions into the Rhône swamps, the Os can apply his Resources Background to Anubians or Spitalians, and gains <b>+1D to social interactions</b> with both Cults.<br/><b>EQUIPMENT:</b> Radio; Assault rifle; Marduk oil (8 doses); Sanglier marker (blood samples enhanced with Pheromancer ichor; used by the Sanglier to locate each other in the thicket)`,

  'sanglier-vertebre': 'Vertèbre',
  'sanglier-vertebreDescription': `<b>PREREQUISITE:</b> INT+Science 6, PSY+Cunning 8, PSY+Faith/Willpower 6, Allies 2, Network 2<br/><b>RESULT:</b> Vertèbre are the Clan’s foundation. They hold important positions in the city government, they represent the Clan outside their hometown, and squabble with each other for prestige in the eyes of their family’s Ventricule and the Clan’s Cerveau. There is no way past them if you want to be involved in anything in Montpellier. They organize forced marriages, evaluate newcomers with the help of blood tests, and even influence the Neolibyan slave trade. The intrigues of the Vertèbre are opaque and intricate; they add <b>+2D PSY+Cunning</b> when trying to avoid being caught in a lie.<br/><b>EQUIPMENT:</b> Walking cane with crest of their respective house and hidden stiletto; Poisons; Vials with blood clotting agents; Miniature Pheromancer idol`,

  'sanglier-ventricule': 'Ventricule',
  'sanglier-ventriculeDescription': `<b>PREREQUISITE:</b> CHA+Leadership 8, PSY+Faith/Willpower 8, INS+Empathy 6, Authority 4, Resources 3; The old Ventricule of their family must die<br/><b>RESULT:</b> The Ventricule is the leader of his house, setting out the decrees and ideals which his brethren and descendants must adhere to. He is the arbiter of standing within his family, able to pick and choose which Baisse is elevated to Sang, approve or deny the choices of the Veine, and where to deploy the Os and their squads. The only voices which rise above his are those of the Cerveau and Neurone.<br/><br/>Many of the old families own complete streets in Montpellier, gaining a fortune from renting the houses out. The Ventricule also defends his bloodline against the machinations of his rivals and tries to strengthen his family’s influence with the Cerveau.<br/><b>EQUIPMENT:</b> Signet Ring, bearing the mark of their family. Any documents or proclamations sealed with this sign carry the full weight of the Ventricule`,

  'sanglier-neurone': 'Neurone',
  'sanglier-neuroneDescription': `<b>PREREQUISITE:</b> AGI+Projectiles 10, CHA+Leadership 10, PSY+Faith/Willpower 10, Renown 5, Authority 5<br/><b>RESULT:</b> There is always a single Neurone commanding the Sanglier legion, overseeing the movements of the Os squads, deliberating over missions into the jungles with the Ventricules, and negotiating with the Cults to send and receive aid. Together with the Cerveau, he leads the Clan. If the Cerveau dies, the Neurone appoints her successor.<br/><br/>The Neurone is only activated in the direst cases of emergency. He represents the highest life form of the Sanglier. His position makes others walk through the fire for him. At the same time, he has access to the holiest arsenals of the Sanglier.<br/><b>EQUIPMENT:</b> Red Kevlar vest; Heavy pistol; Cartridges of nerve agent; Blowgun with darts coated in viper toxin`,

  'sanglier-cerveau': 'Cerveau',
  'sanglier-cerveauDescription': `<b>PREREQUISITE:</b> INT+Science 10, CHA+Expression 10, PSY+Cunning 10, Authority 5, Secrets 5<br/><b>RESULT:</b> If the Neurone is the body of the Sanglier, the Cerveau is their mind. While the Neurone turns his gaze outwards to the world beyond Montpellier, the Cerveau deals with matters closer to home. She guards all of the Sanglier family trees, cultivating the Sanglier bloodline through the generations like a treasured garden. Should the Neurone ever die, she is the one to appoint his successor.<br/><br/>The Cerveau has a single, driving task: find the new King of Franka. In her search for the blue blood of the Regent, the Cerveau is permitted to use the entire resources of her Clan, demand that women of good stock bear children, marry off entire families in the pursuit of higher quality offspring, and similarly cut off entire branches of the Sanglier should their blood be sullied.<br/><br/>When the time comes for her position to pass on to a worthy successor, she will bestow on them extensive records of the Sanglier bloodline going back centuries, and call on them to continue the task.<br/><b>EQUIPMENT:</b> Hematite scepter; Tome containing the family trees of all houses`
}

const sanglierPotentials = {
  bloodCall: 'Blood Call',
  bloodCallDescription: `<b>PREREQUISITE:</b> Faith<br/><br/><b>RESULT:</b> When preparing for combat, the Sanglier legionnaires mix their blood with a little Petro and burn it to obtain the blessing of the Cerveau. If a Sanglier sacrifices his blood before a battle, taking <b>(1) Flesh Wound</b> of Damage, he gains a bonus equal to his <b>Potential Level to his Passive Defense</b> until the end of the combat.`
}

const bordenoirClans = {
  bordenoir: 'Bordenoir',
  bordenoirDescription: `The <b>Bordenoir</b> are a <b>Tech Level III</b> Clan based in <b>Perpignan</b>, created from several smaller peoples who learned that survival depended less upon ancestry than upon cooperation, competence, and defending their territory together. Their lands are marked by the <b>Black Border</b>, within which Frankans, Hybrispanians, Africans, Jehammedans, and others are expected to put aside outside conflicts and obey Bordenoir law; anyone capable and willing to contribute can potentially become part of the Clan. Life revolves around both <b>the Mediterranean and the Pyrenees</b>: Faucons patrol the coast and fishing fleets against pirates, smugglers, sharks, and other threats, while Capricornes and Mineurs venture into the mountains to extract valuable silver and maintain relations with local Jehammedans. Politically, the Bordenoir prize independence and carefully balance their dealings with Neolibyans, Scourgers, and other powerful outsiders, preferring hardship to becoming dependent upon foreign protection. Perpignan is ultimately governed by the elderly <b>Council of Crânes</b>, while elected Colonels represent individual districts and the formidable <b>Poing</b> leads the Clan's warriors. In short, the Bordenoir are <b>Franka's fiercely independent coastal guardians</b>—fishermen, miners, sailors, soldiers, and negotiators united not by pure blood but by the conviction that anyone who helps defend Perpignan belongs.`
}

const bordenoirRanks = {
  'bordenoir-mouton': 'Mouton',
  'bordenoir-moutonDescription': `<b>PREREQUISITE:</b> -<br/><b>RESULT:</b> The Bordenoir remember their history, a disparate, unfocused conglomerate of Clans compressed until the breaking point came. The union of the old, separated families and tribes was what gave them strength in the past, and it’s what gives them identity today. Anyone who is willing to contribute can become a member of the Bordenoir, no matter their origin or background. Frankans, Hybrispanians, Africans, it doesn’t matter. They are all marked with the insignia of the Bordenoir, a tattoo with ink made from black soot, placed on the back of the hand, allowing any member of the Clan to recognise his new brethren.<br/><br/>From there, the newly crowned Mouton gets to work in and around Perpignan. As fishermen, blacksmiths, bakers, butchers, farmers, and almost any other niche, the Mouton contributes to his new Clan, and proves his worth.<br/><b>EQUIPMENT:</b> Excellent maps of the Pyrenees and the southern coast of Franka`,

  'bordenoir-capricorne': 'Capricorne',
  'bordenoir-capricorneDescription': `<b>PREREQUISITE:</b> BOD+Athletics 6, AGI+Crafting 6, Allies 1<br/><b>RESULT:</b> There are two distinct disciplines breaking away from the traditional path of the Bordenoir, and the Capricorne has chosen to follow one. The monotony of toiling away in a shop or farm doesn’t appeal to him, and he doesn’t have the sea legs to spend all day every day out on a boat catching fish. Instead, he turns his eyes to the Pyrenees, buying or renting some excavation gear and joining up with a team heading along the old mountain paths. Up there he and his fellow Clanners get to work digging into the guts of the earth, chiseling chunks of ore from the walls of the ancient tunnels or creating new branches to the mines. When his team hauls the score back to Perpignan or to the camps of the Jehammedans living nearby, he gets a share of the profit for his effort.<br/><br/>While up in the mountains, he makes contact with the Jehammedans and becomes good friends with the Abrami and Ismaeli of the tribes. They’ll let him pass along the safer paths without paying a toll, and give him some advice on how to handle these areas: the Capricorne adds <b>+2D to INS+Survival and BOD+Athletics</b> in mountainous terrain.<br/><b>EQUIPMENT:</b> Climbing gear; Pickaxe`,

  'bordenoir-faucon': 'Faucon',
  'bordenoir-fauconDescription': `<b>PREREQUISITE:</b> BOD+Toughness 4, AGI+Projectiles 6, AGI+Navigation 6<br/><b>RESULT:</b> The rushing wind whips through his hair, the spray from the waters below makes the air taste of salt, the sway of his ship forces him to adjust his balance. It all feels right. The crack of a cannon breaks the moment as the Faucon gets to work, defending his people and home.<br/><br/>Out on the Mediterranean is where the Faucon knows he belongs, and his task is essential. Franka is a dangerous place, with strange beasts prowling inland and vicious pirates circling offshore. The massed ranks of the Bordenoir need defending from these threats, and the Faucon provides. He takes up the sword and harpoon, patrolling the waters and land around Perpignan, keeping the Moutons safe—to them, he’s a hero. The Faucon gains <b>Allies (+1)</b>.<br/><b>EQUIPMENT:</b> Pneumatic harpoon (harpoon crossbow); Dhow; Binoculars; Flare gun`,

  'bordenoir-mineur': 'Mineur',
  'bordenoir-mineurDescription': `<b>PREREQUISITE:</b> AGI+Crafting 8, INT+Legends 6, INS+Orienteering 6, Network 2, Resources 2<br/><b>RESULT:</b> Anyone with a modicum of common sense and a bit of brawn can grab a pickaxe and start digging. Good enough to scrape by, picking up a few chunks of iron or silver here and there, but that’s not where the real money lies. The Mineur has shown the spark of ingenuity needed to track down the worthwhile spots, whether by studying old mining maps of the region or by intuitively understanding the lay of the land. Now, he puts together his own expeditions, securing loans from the Council of Crânes to hire on Capricornes and procure equipment, leading his new crew out into the Pyrenees. He has <b>Resources and Network (+2)</b> when supported by a loan until they return to Perpignan, but if his endeavor fails he’ll need another way to pay his debts. Good luck.<br/><br/>In the meantime, he keeps up his communication with the Jehammedan tribes in the Pyrenean hills—while once it was a passing friendship, now it’s part of business. A few small nuggets of gold and silver as payment for his crew’s safe passage, along with news from Hybrispania and any other developments occurring in the area, so long as he doesn’t bother the Hagari. His <b>Network rises by (+2)</b>.<br/><b>EQUIPMENT:</b> Revolver; Mule; Notebook with exceptionally detailed mountain maps of the region`,

  'bordenoir-moniteur': 'Moniteur',
  'bordenoir-moniteurDescription': `<b>PREREQUISITE:</b> BOD+Toughness 6, AGI+Navigation 8, PSY+Reaction 6, Allies 3, Authority 1<br/><b>RESULT:</b> The Moniteurs each lead a squad of five Faucons, a tightly knit group patrolling the area around Perpignan. On the water he circles the fishing fleet in a well-armed speedboat, while on land he stands on the rear platform of a Kom acquired from the Africans. The cost of Petro is high, but the security and force projection it offers the Bordenoir’s enforcers is well worth it. Not to mention the terror a Moniteur inspires in his prey when the rattling of an engine is bearing down on them—the Bordenoir have no time for mercy, and their laws were built when it seemed the whole world was allied against them. Punishment is swift, and brutal.<br/><br/>While there is no love lost between the Bordenoir and the Neolibyan traders, the cunning Africans are easily able to recognise a situation that plays to their benefit—the Faucons and Moniteurs might only intend to protect their own Clan, but by extension they’re protecting the Neolibyans. As such, Moniteurs are showered with subsidies and gifts from the Africans; standard operating equipment and food is free for himself and his Faucons, he buys Petro at half price, and African Scrappers upgrade his vehicle at discount rates.<br/><b>EQUIPMENT:</b> Revolver; Speedboat or Kom; Grappling hook`
}

const bordenoirPotentials = {
  lanceThrust: 'Lance Thrust',
  lanceThrustDescription: `<b>PREREQUISITE:</b> Focus<br/><br/><b>RESULT:</b> Any good fisherman knows how to thrust for the brain to kill a tiger shark immediately. Dodge and thrust. The Bordenoir exhibit lethal precision in melee, targeting their enemy’s most vulnerable areas. Characters with this Potential add <b>+1D per Potential Level to Aimed Attack rolls in close combat</b>.`
}
